"""Debug logging for the SDK.

Originally generated by Speakeasy, now hand-maintained and listed in `.genignore`
so a regeneration cannot reinstate the `logging.basicConfig` call below — see
`get_default_logger`.
"""

import httpx
import logging
import os
from typing import Any, Protocol


class Logger(Protocol):
    def debug(self, msg: str, *args: Any, **kwargs: Any) -> None:
        pass


class NoOpLogger:
    def debug(self, msg: str, *args: Any, **kwargs: Any) -> None:
        pass


def get_body_content(req: httpx.Request) -> str:
    return "<streaming body>" if not hasattr(req, "_content") else str(req.content)


def get_default_logger() -> Logger:
    """Return the debug logger used when `OPENROUTER_DEBUG` is set.

    Configuration is scoped to the `openrouter` logger. A library must not call
    `logging.basicConfig`: that sets the level and attaches a handler on the
    *root* logger, turning on DEBUG output for every library in the process and
    overriding whatever logging the host application had already set up.

    A `StreamHandler` is only attached when nothing up the hierarchy would emit
    the records already, so an application that has configured its own handlers
    keeps them, and repeated client construction does not stack duplicates.
    """
    if os.getenv("OPENROUTER_DEBUG"):
        logger = logging.getLogger("openrouter")
        logger.setLevel(logging.DEBUG)
        if not logger.hasHandlers():
            logger.addHandler(logging.StreamHandler())
        return logger
    return NoOpLogger()
