"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from openrouter.types import BaseModel
from typing_extensions import TypedDict


class ChatCompletionMessageToolCallType(str, Enum):
    FUNCTION = "function"


class ChatCompletionMessageToolCallFunctionTypedDict(TypedDict):
    name: str
    r"""Function name to call"""
    arguments: str
    r"""Function arguments as JSON string"""


class ChatCompletionMessageToolCallFunction(BaseModel):
    name: str
    r"""Function name to call"""

    arguments: str
    r"""Function arguments as JSON string"""


class ChatCompletionMessageToolCallTypedDict(TypedDict):
    r"""Tool call made by the assistant"""

    id: str
    r"""Tool call identifier"""
    type: ChatCompletionMessageToolCallType
    function: ChatCompletionMessageToolCallFunctionTypedDict


class ChatCompletionMessageToolCall(BaseModel):
    r"""Tool call made by the assistant"""

    id: str
    r"""Tool call identifier"""

    type: ChatCompletionMessageToolCallType

    function: ChatCompletionMessageToolCallFunction
