"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .chatcompletioncontentpart import (
    ChatCompletionContentPart,
    ChatCompletionContentPartTypedDict,
)
from enum import Enum
from openrouter.types import BaseModel
from typing import List, Optional, Union
from typing_extensions import NotRequired, TypeAliasType, TypedDict


class ChatCompletionUserMessageParamRole(str, Enum):
    USER = "user"


ChatCompletionUserMessageParamContentTypedDict = TypeAliasType(
    "ChatCompletionUserMessageParamContentTypedDict",
    Union[str, List[ChatCompletionContentPartTypedDict]],
)
r"""User message content"""


ChatCompletionUserMessageParamContent = TypeAliasType(
    "ChatCompletionUserMessageParamContent", Union[str, List[ChatCompletionContentPart]]
)
r"""User message content"""


class ChatCompletionUserMessageParamTypedDict(TypedDict):
    r"""User message"""

    role: ChatCompletionUserMessageParamRole
    content: ChatCompletionUserMessageParamContentTypedDict
    r"""User message content"""
    name: NotRequired[str]
    r"""Optional name for the user"""


class ChatCompletionUserMessageParam(BaseModel):
    r"""User message"""

    role: ChatCompletionUserMessageParamRole

    content: ChatCompletionUserMessageParamContent
    r"""User message content"""

    name: Optional[str] = None
    r"""Optional name for the user"""
