"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openrouter.types import BaseModel
from typing import Literal, Optional
from typing_extensions import NotRequired, TypedDict


ChatCompletionContentPartImageType = Literal["image_url"]

Detail = Literal["auto", "low", "high"]
r"""Image detail level for vision models"""


class ChatCompletionContentPartImageImageURLTypedDict(TypedDict):
    url: str
    r"""URL of the image (data: URLs supported)"""
    detail: NotRequired[Detail]
    r"""Image detail level for vision models"""


class ChatCompletionContentPartImageImageURL(BaseModel):
    url: str
    r"""URL of the image (data: URLs supported)"""

    detail: Optional[Detail] = None
    r"""Image detail level for vision models"""


class ChatCompletionContentPartImageTypedDict(TypedDict):
    r"""Image content part for vision models"""

    type: ChatCompletionContentPartImageType
    image_url: ChatCompletionContentPartImageImageURLTypedDict


class ChatCompletionContentPartImage(BaseModel):
    r"""Image content part for vision models"""

    type: ChatCompletionContentPartImageType

    image_url: ChatCompletionContentPartImageImageURL
