"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from openrouter.types import BaseModel
import pydantic
from typing_extensions import Annotated, TypedDict


class ChatCompletionContentPartAudioType(str, Enum):
    INPUT_AUDIO = "input_audio"


class ChatCompletionContentPartAudioFormat(str, Enum):
    r"""Audio format"""

    WAV = "wav"
    MP3 = "mp3"
    FLAC = "flac"
    M4A = "m4a"
    OGG = "ogg"
    PCM16 = "pcm16"
    PCM24 = "pcm24"


class InputAudioTypedDict(TypedDict):
    data: str
    r"""Base64 encoded audio data"""
    format_: ChatCompletionContentPartAudioFormat
    r"""Audio format"""


class InputAudio(BaseModel):
    data: str
    r"""Base64 encoded audio data"""

    format_: Annotated[
        ChatCompletionContentPartAudioFormat, pydantic.Field(alias="format")
    ]
    r"""Audio format"""


class ChatCompletionContentPartAudioTypedDict(TypedDict):
    r"""Audio input content part"""

    type: ChatCompletionContentPartAudioType
    input_audio: InputAudioTypedDict


class ChatCompletionContentPartAudio(BaseModel):
    r"""Audio input content part"""

    type: ChatCompletionContentPartAudioType

    input_audio: InputAudio
