"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .chatcompletionassistantmessageparam import (
    ChatCompletionAssistantMessageParam,
    ChatCompletionAssistantMessageParamTypedDict,
)
from .chatcompletionsystemmessageparam import (
    ChatCompletionSystemMessageParam,
    ChatCompletionSystemMessageParamTypedDict,
)
from .chatcompletiontoolmessageparam import (
    ChatCompletionToolMessageParam,
    ChatCompletionToolMessageParamTypedDict,
)
from .chatcompletionusermessageparam import (
    ChatCompletionUserMessageParam,
    ChatCompletionUserMessageParamTypedDict,
)
from openrouter.utils import get_discriminator
from pydantic import Discriminator, Tag
from typing import Union
from typing_extensions import Annotated, TypeAliasType


ChatCompletionMessageParamTypedDict = TypeAliasType(
    "ChatCompletionMessageParamTypedDict",
    Union[
        ChatCompletionSystemMessageParamTypedDict,
        ChatCompletionUserMessageParamTypedDict,
        ChatCompletionToolMessageParamTypedDict,
        ChatCompletionAssistantMessageParamTypedDict,
    ],
)
r"""Chat completion message with role-based discrimination"""


ChatCompletionMessageParam = Annotated[
    Union[
        Annotated[ChatCompletionSystemMessageParam, Tag("system")],
        Annotated[ChatCompletionUserMessageParam, Tag("user")],
        Annotated[ChatCompletionAssistantMessageParam, Tag("assistant")],
        Annotated[ChatCompletionToolMessageParam, Tag("tool")],
    ],
    Discriminator(lambda m: get_discriminator(m, "role", "role")),
]
r"""Chat completion message with role-based discrimination"""
