"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .chatcompletioncontentpart import (
    ChatCompletionContentPart,
    ChatCompletionContentPartTypedDict,
)
from enum import Enum
from openrouter.types import BaseModel
from typing import List, Union
from typing_extensions import TypeAliasType, TypedDict


class ChatCompletionToolMessageParamRole(str, Enum):
    TOOL = "tool"


ChatCompletionToolMessageParamContentTypedDict = TypeAliasType(
    "ChatCompletionToolMessageParamContentTypedDict",
    Union[str, List[ChatCompletionContentPartTypedDict]],
)
r"""Tool response content"""


ChatCompletionToolMessageParamContent = TypeAliasType(
    "ChatCompletionToolMessageParamContent", Union[str, List[ChatCompletionContentPart]]
)
r"""Tool response content"""


class ChatCompletionToolMessageParamTypedDict(TypedDict):
    r"""Tool response message"""

    role: ChatCompletionToolMessageParamRole
    content: ChatCompletionToolMessageParamContentTypedDict
    r"""Tool response content"""
    tool_call_id: str
    r"""ID of the tool call this message responds to"""


class ChatCompletionToolMessageParam(BaseModel):
    r"""Tool response message"""

    role: ChatCompletionToolMessageParamRole

    content: ChatCompletionToolMessageParamContent
    r"""Tool response content"""

    tool_call_id: str
    r"""ID of the tool call this message responds to"""
