"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from openrouter.types import BaseModel
from typing_extensions import TypedDict


class ChatCompletionNamedToolChoiceType(str, Enum):
    FUNCTION = "function"


class ChatCompletionNamedToolChoiceFunctionTypedDict(TypedDict):
    name: str
    r"""Function name to call"""


class ChatCompletionNamedToolChoiceFunction(BaseModel):
    name: str
    r"""Function name to call"""


class ChatCompletionNamedToolChoiceTypedDict(TypedDict):
    r"""Named tool choice for specific function"""

    type: ChatCompletionNamedToolChoiceType
    function: ChatCompletionNamedToolChoiceFunctionTypedDict


class ChatCompletionNamedToolChoice(BaseModel):
    r"""Named tool choice for specific function"""

    type: ChatCompletionNamedToolChoiceType

    function: ChatCompletionNamedToolChoiceFunction
