"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openrouter.types import BaseModel
from typing import Literal, Optional
from typing_extensions import NotRequired, TypedDict


URLCitationAnnotationDetailType = Literal["url_citation",]


class URLCitationTypedDict(TypedDict):
    end_index: float
    start_index: float
    title: str
    url: str
    content: NotRequired[str]


class URLCitation(BaseModel):
    end_index: float

    start_index: float

    title: str

    url: str

    content: Optional[str] = None


class URLCitationAnnotationDetailTypedDict(TypedDict):
    r"""URL citation annotation"""

    type: URLCitationAnnotationDetailType
    url_citation: URLCitationTypedDict


class URLCitationAnnotationDetail(BaseModel):
    r"""URL citation annotation"""

    type: URLCitationAnnotationDetailType

    url_citation: URLCitation
