"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from typing import TYPE_CHECKING
from importlib import import_module
import builtins

if TYPE_CHECKING:
    from .chatcompletionerror import ChatCompletionError, ChatCompletionErrorData
    from .no_response_error import NoResponseError
    from .openrouterdefaulterror import OpenRouterDefaultError
    from .openroutererror import OpenRouterError
    from .responsevalidationerror import ResponseValidationError

__all__ = [
    "ChatCompletionError",
    "ChatCompletionErrorData",
    "NoResponseError",
    "OpenRouterDefaultError",
    "OpenRouterError",
    "ResponseValidationError",
]

_dynamic_imports: dict[str, str] = {
    "ChatCompletionError": ".chatcompletionerror",
    "ChatCompletionErrorData": ".chatcompletionerror",
    "NoResponseError": ".no_response_error",
    "OpenRouterDefaultError": ".openrouterdefaulterror",
    "OpenRouterError": ".openroutererror",
    "ResponseValidationError": ".responsevalidationerror",
}


def __getattr__(attr_name: str) -> object:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(
            f"No {attr_name} found in _dynamic_imports for module name -> {__name__} "
        )

    try:
        module = import_module(module_name, __package__)
        result = getattr(module, attr_name)
        return result
    except ImportError as e:
        raise ImportError(
            f"Failed to import {attr_name} from {module_name}: {e}"
        ) from e
    except AttributeError as e:
        raise AttributeError(
            f"Failed to get {attr_name} from {module_name}: {e}"
        ) from e


def __dir__():
    lazy_attrs = builtins.list(_dynamic_imports.keys())
    return builtins.sorted(lazy_attrs)
