"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .badgatewayresponse_error import BadGatewayResponseErrorData
from .conflictresponse_error import ConflictResponseErrorData
from .createprivateendpointvalidationfailedresponse_error import (
    CreatePrivateEndpointValidationFailedResponseErrorData,
)
from .internalserverresponse_error import InternalServerResponseErrorData
from .notfoundresponse_error import NotFoundResponseErrorData
from .unprocessableentityresponse_error import UnprocessableEntityResponseErrorData
from dataclasses import dataclass, field
import httpx
from openrouter.errors import OpenRouterError
from typing import Optional, Union
from typing_extensions import TypeAliasType


BadGatewayUnion = TypeAliasType(
    "BadGatewayUnion",
    Union[
        CreatePrivateEndpointValidationFailedResponseErrorData,
        BadGatewayResponseErrorData,
    ],
)
r"""An upstream dependency failed. When `activate` was passed and the draft was created, `data` carries it and any validation checks."""


@dataclass(unsafe_hash=True)
class BadGateway(OpenRouterError):
    r"""An upstream dependency failed. When `activate` was passed and the draft was created, `data` carries it and any validation checks."""

    data: BadGatewayUnion = field(hash=False)

    def __init__(
        self,
        data: BadGatewayUnion,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


InternalServerErrorUnion = TypeAliasType(
    "InternalServerErrorUnion",
    Union[
        CreatePrivateEndpointValidationFailedResponseErrorData,
        InternalServerResponseErrorData,
    ],
)
r"""Internal server error. When `activate` was passed and the draft was created, `data` carries it and any validation checks."""


@dataclass(unsafe_hash=True)
class InternalServerError(OpenRouterError):
    r"""Internal server error. When `activate` was passed and the draft was created, `data` carries it and any validation checks."""

    data: InternalServerErrorUnion = field(hash=False)

    def __init__(
        self,
        data: InternalServerErrorUnion,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


UnprocessableEntityUnion = TypeAliasType(
    "UnprocessableEntityUnion",
    Union[
        CreatePrivateEndpointValidationFailedResponseErrorData,
        UnprocessableEntityResponseErrorData,
    ],
)
r"""The request was invalid, or validation failed. When `activate` was passed and the draft was created, `data` carries it and any validation checks."""


@dataclass(unsafe_hash=True)
class UnprocessableEntity(OpenRouterError):
    r"""The request was invalid, or validation failed. When `activate` was passed and the draft was created, `data` carries it and any validation checks."""

    data: UnprocessableEntityUnion = field(hash=False)

    def __init__(
        self,
        data: UnprocessableEntityUnion,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


ConflictUnion = TypeAliasType(
    "ConflictUnion",
    Union[
        CreatePrivateEndpointValidationFailedResponseErrorData,
        ConflictResponseErrorData,
    ],
)
r"""The request conflicts with the endpoint state, such as a stale validation. When `activate` was passed and the draft was created, `data` carries it and any validation checks."""


@dataclass(unsafe_hash=True)
class Conflict(OpenRouterError):
    r"""The request conflicts with the endpoint state, such as a stale validation. When `activate` was passed and the draft was created, `data` carries it and any validation checks."""

    data: ConflictUnion = field(hash=False)

    def __init__(
        self,
        data: ConflictUnion,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


NotFoundUnion = TypeAliasType(
    "NotFoundUnion",
    Union[
        CreatePrivateEndpointValidationFailedResponseErrorData,
        NotFoundResponseErrorData,
    ],
)
r"""The model, provider, or validation workspace was not found. When `activate` was passed and the draft was created, `data` carries it and any validation checks."""


@dataclass(unsafe_hash=True)
class NotFound(OpenRouterError):
    r"""The model, provider, or validation workspace was not found. When `activate` was passed and the draft was created, `data` carries it and any validation checks."""

    data: NotFoundUnion = field(hash=False)

    def __init__(
        self,
        data: NotFoundUnion,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
