"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dataclasses import dataclass, field
import httpx
from openrouter.components import internchaterror as components_internchaterror
from openrouter.errors import OpenRouterError
from openrouter.types import BaseModel
from typing import Optional


class InternChatErrorResponseData(BaseModel):
    error: components_internchaterror.InternChatError
    r"""The OpenAI-compatible error object. `metadata` is present on refusals from the chat route. Authentication refusals (`401`), the departed-creator `403` and the programme `404` carry only `code` and `message`."""


@dataclass(unsafe_hash=True)
class InternChatErrorResponse(OpenRouterError):
    r"""A refusal before the stream opens. Once the response is `200` and streaming, failures arrive as a chunk with `finish_reason: \"error\"` instead."""

    data: InternChatErrorResponseData = field(hash=False)

    def __init__(
        self,
        data: InternChatErrorResponseData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.error.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
