"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dataclasses import dataclass, field
import httpx
from openrouter.components import (
    internlifecycleerror as components_internlifecycleerror,
)
from openrouter.errors import OpenRouterError
from openrouter.types import BaseModel
from typing import Optional


class InternLifecycleErrorData(BaseModel):
    error: components_internlifecycleerror.InternLifecycleErrorError


@dataclass(unsafe_hash=True)
class InternLifecycleError(OpenRouterError):
    r"""Intern lifecycle request failure."""

    data: InternLifecycleErrorData = field(hash=False)

    def __init__(
        self,
        data: InternLifecycleErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.error.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
