"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .alignmentcallrecord import AlignmentCallRecord, AlignmentCallRecordTypedDict
from openrouter.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class AlignmentTypedDict(TypedDict):
    r"""Beta. The result of the alignment plugin for this request; the shape may change."""

    calls: List[AlignmentCallRecordTypedDict]
    r"""One record per evaluated assistant message of the request, in the order the messages were produced."""


class Alignment(BaseModel):
    r"""Beta. The result of the alignment plugin for this request; the shape may change."""

    calls: List[AlignmentCallRecord]
    r"""One record per evaluated assistant message of the request, in the order the messages were produced."""
