"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openrouter.types import BaseModel
from typing import Literal
from typing_extensions import TypedDict


class AlignmentChatToolCallFunctionTypedDict(TypedDict):
    arguments: str
    name: str


class AlignmentChatToolCallFunction(BaseModel):
    arguments: str

    name: str


AlignmentChatToolCallType = Literal["function",]


class AlignmentChatToolCallTypedDict(TypedDict):
    function: AlignmentChatToolCallFunctionTypedDict
    id: str
    type: AlignmentChatToolCallType


class AlignmentChatToolCall(BaseModel):
    function: AlignmentChatToolCallFunction

    id: str

    type: AlignmentChatToolCallType
