"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .alignmentchatrejected import AlignmentChatRejected, AlignmentChatRejectedTypedDict
from .alignmentresponsesrejected import (
    AlignmentResponsesRejected,
    AlignmentResponsesRejectedTypedDict,
)
from typing import List, Union
from typing_extensions import TypeAliasType


AlignmentRejectedTypedDict = TypeAliasType(
    "AlignmentRejectedTypedDict",
    Union[AlignmentChatRejectedTypedDict, List[AlignmentResponsesRejectedTypedDict]],
)


AlignmentRejected = TypeAliasType(
    "AlignmentRejected", Union[AlignmentChatRejected, List[AlignmentResponsesRejected]]
)
