"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .anthropiccodeexecutionoutput import (
    AnthropicCodeExecutionOutput,
    AnthropicCodeExecutionOutputTypedDict,
)
from openrouter.types import BaseModel
from typing import List, Literal
from typing_extensions import TypedDict


AnthropicCodeExecutionResultType = Literal["code_execution_result",]


class AnthropicCodeExecutionResultTypedDict(TypedDict):
    content: List[AnthropicCodeExecutionOutputTypedDict]
    return_code: int
    stderr: str
    stdout: str
    type: AnthropicCodeExecutionResultType


class AnthropicCodeExecutionResult(BaseModel):
    content: List[AnthropicCodeExecutionOutput]

    return_code: int

    stderr: str

    stdout: str

    type: AnthropicCodeExecutionResultType
