"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openrouter.types import BaseModel
from typing import Literal
from typing_extensions import TypedDict


AnthropicRedactedThinkingBlockType = Literal["redacted_thinking",]


class AnthropicRedactedThinkingBlockTypedDict(TypedDict):
    data: str
    type: AnthropicRedactedThinkingBlockType


class AnthropicRedactedThinkingBlock(BaseModel):
    data: str

    type: AnthropicRedactedThinkingBlockType
