"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openrouter.types import BaseModel
from typing_extensions import TypedDict


class AnthropicCitationsConfigTypedDict(TypedDict):
    enabled: bool


class AnthropicCitationsConfig(BaseModel):
    enabled: bool
