"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .anthropictexteditorcodeexecutioncontent import (
    AnthropicTextEditorCodeExecutionContent,
    AnthropicTextEditorCodeExecutionContentTypedDict,
)
from openrouter.types import BaseModel
from typing import Literal
from typing_extensions import TypedDict


AnthropicTextEditorCodeExecutionToolResultType = Literal[
    "text_editor_code_execution_tool_result",
]


class AnthropicTextEditorCodeExecutionToolResultTypedDict(TypedDict):
    content: AnthropicTextEditorCodeExecutionContentTypedDict
    tool_use_id: str
    type: AnthropicTextEditorCodeExecutionToolResultType


class AnthropicTextEditorCodeExecutionToolResult(BaseModel):
    content: AnthropicTextEditorCodeExecutionContent

    tool_use_id: str

    type: AnthropicTextEditorCodeExecutionToolResultType
