"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .anthropiciterationcachecreation import (
    AnthropicIterationCacheCreation,
    AnthropicIterationCacheCreationTypedDict,
)
from openrouter.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import Literal, Optional
from typing_extensions import NotRequired, TypedDict


AnthropicMessageUsageIterationType = Literal["message",]


class AnthropicMessageUsageIterationTypedDict(TypedDict):
    type: AnthropicMessageUsageIterationType
    cache_creation: NotRequired[Nullable[AnthropicIterationCacheCreationTypedDict]]
    cache_creation_input_tokens: NotRequired[int]
    cache_read_input_tokens: NotRequired[int]
    input_tokens: NotRequired[int]
    output_tokens: NotRequired[int]
    model: NotRequired[str]


class AnthropicMessageUsageIteration(BaseModel):
    type: AnthropicMessageUsageIterationType

    cache_creation: OptionalNullable[AnthropicIterationCacheCreation] = UNSET

    cache_creation_input_tokens: Optional[int] = None

    cache_read_input_tokens: Optional[int] = None

    input_tokens: Optional[int] = None

    output_tokens: Optional[int] = None

    model: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = [
            "cache_creation",
            "cache_creation_input_tokens",
            "cache_read_input_tokens",
            "input_tokens",
            "output_tokens",
            "model",
        ]
        nullable_fields = ["cache_creation"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
