"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openrouter.types import BaseModel, Nullable, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Literal
from typing_extensions import TypedDict


AnthropicTextEditorCodeExecutionStrReplaceResultType = Literal[
    "text_editor_code_execution_str_replace_result",
]


class AnthropicTextEditorCodeExecutionStrReplaceResultTypedDict(TypedDict):
    lines: Nullable[List[str]]
    new_lines: Nullable[int]
    new_start: Nullable[int]
    old_lines: Nullable[int]
    old_start: Nullable[int]
    type: AnthropicTextEditorCodeExecutionStrReplaceResultType


class AnthropicTextEditorCodeExecutionStrReplaceResult(BaseModel):
    lines: Nullable[List[str]]

    new_lines: Nullable[int]

    new_start: Nullable[int]

    old_lines: Nullable[int]

    old_start: Nullable[int]

    type: AnthropicTextEditorCodeExecutionStrReplaceResultType

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m
