"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .anthropiccaller import AnthropicCaller, AnthropicCallerTypedDict
from .anthropicwebsearchresult import (
    AnthropicWebSearchResult,
    AnthropicWebSearchResultTypedDict,
)
from .anthropicwebsearchtoolresulterror import (
    AnthropicWebSearchToolResultError,
    AnthropicWebSearchToolResultErrorTypedDict,
)
from openrouter.types import BaseModel
from typing import List, Literal, Union
from typing_extensions import TypeAliasType, TypedDict


AnthropicWebSearchToolResultContentTypedDict = TypeAliasType(
    "AnthropicWebSearchToolResultContentTypedDict",
    Union[
        AnthropicWebSearchToolResultErrorTypedDict,
        List[AnthropicWebSearchResultTypedDict],
    ],
)


AnthropicWebSearchToolResultContent = TypeAliasType(
    "AnthropicWebSearchToolResultContent",
    Union[AnthropicWebSearchToolResultError, List[AnthropicWebSearchResult]],
)


AnthropicWebSearchToolResultType = Literal["web_search_tool_result",]


class AnthropicWebSearchToolResultTypedDict(TypedDict):
    caller: AnthropicCallerTypedDict
    content: AnthropicWebSearchToolResultContentTypedDict
    tool_use_id: str
    type: AnthropicWebSearchToolResultType


class AnthropicWebSearchToolResult(BaseModel):
    caller: AnthropicCaller

    content: AnthropicWebSearchToolResultContent

    tool_use_id: str

    type: AnthropicWebSearchToolResultType
