"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .anthropiccodeexecutionoutput import (
    AnthropicCodeExecutionOutput,
    AnthropicCodeExecutionOutputTypedDict,
)
from openrouter.types import BaseModel
from typing import List, Literal
from typing_extensions import TypedDict


AnthropicEncryptedCodeExecutionResultType = Literal["encrypted_code_execution_result",]


class AnthropicEncryptedCodeExecutionResultTypedDict(TypedDict):
    content: List[AnthropicCodeExecutionOutputTypedDict]
    encrypted_stdout: str
    return_code: int
    stderr: str
    type: AnthropicEncryptedCodeExecutionResultType


class AnthropicEncryptedCodeExecutionResult(BaseModel):
    content: List[AnthropicCodeExecutionOutput]

    encrypted_stdout: str

    return_code: int

    stderr: str

    type: AnthropicEncryptedCodeExecutionResultType
