"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .anthropiccodeexecutionresult import (
    AnthropicCodeExecutionResult,
    AnthropicCodeExecutionResultTypedDict,
)
from .anthropiccodeexecutiontoolresulterror import (
    AnthropicCodeExecutionToolResultError,
    AnthropicCodeExecutionToolResultErrorTypedDict,
)
from .anthropicencryptedcodeexecutionresult import (
    AnthropicEncryptedCodeExecutionResult,
    AnthropicEncryptedCodeExecutionResultTypedDict,
)
from functools import partial
from openrouter.types import BaseModel
from openrouter.utils.unions import parse_open_union
from pydantic import ConfigDict
from pydantic.functional_validators import BeforeValidator
from typing import Any, Literal, Union
from typing_extensions import Annotated, TypeAliasType


AnthropicCodeExecutionContentTypedDict = TypeAliasType(
    "AnthropicCodeExecutionContentTypedDict",
    Union[
        AnthropicCodeExecutionToolResultErrorTypedDict,
        AnthropicCodeExecutionResultTypedDict,
        AnthropicEncryptedCodeExecutionResultTypedDict,
    ],
)


class UnknownAnthropicCodeExecutionContent(BaseModel):
    r"""A AnthropicCodeExecutionContent variant the SDK doesn't recognize. Preserves the raw payload."""

    type: Literal["UNKNOWN"] = "UNKNOWN"
    raw: Any
    is_unknown: Literal[True] = True

    model_config = ConfigDict(frozen=True)


_ANTHROPIC_CODE_EXECUTION_CONTENT_VARIANTS: dict[str, Any] = {
    "code_execution_result": AnthropicCodeExecutionResult,
    "code_execution_tool_result_error": AnthropicCodeExecutionToolResultError,
    "encrypted_code_execution_result": AnthropicEncryptedCodeExecutionResult,
}


AnthropicCodeExecutionContent = Annotated[
    Union[
        AnthropicCodeExecutionResult,
        AnthropicCodeExecutionToolResultError,
        AnthropicEncryptedCodeExecutionResult,
        UnknownAnthropicCodeExecutionContent,
    ],
    BeforeValidator(
        partial(
            parse_open_union,
            disc_key="type",
            variants=_ANTHROPIC_CODE_EXECUTION_CONTENT_VARIANTS,
            unknown_cls=UnknownAnthropicCodeExecutionContent,
            union_name="AnthropicCodeExecutionContent",
        )
    ),
]
