"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openrouter.types import BaseModel
from typing import Literal
from typing_extensions import TypedDict


AnthropicBashCodeExecutionOutputType = Literal["bash_code_execution_output",]


class AnthropicBashCodeExecutionOutputTypedDict(TypedDict):
    file_id: str
    type: AnthropicBashCodeExecutionOutputType


class AnthropicBashCodeExecutionOutput(BaseModel):
    file_id: str

    type: AnthropicBashCodeExecutionOutputType
