"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .anthropictoolreference import (
    AnthropicToolReference,
    AnthropicToolReferenceTypedDict,
)
from openrouter.types import BaseModel
from typing import List, Literal
from typing_extensions import TypedDict


AnthropicToolSearchResultType = Literal["tool_search_tool_search_result",]


class AnthropicToolSearchResultTypedDict(TypedDict):
    tool_references: List[AnthropicToolReferenceTypedDict]
    type: AnthropicToolSearchResultType


class AnthropicToolSearchResult(BaseModel):
    tool_references: List[AnthropicToolReference]

    type: AnthropicToolSearchResultType
