"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .anthropiccitationcharlocation import (
    AnthropicCitationCharLocation,
    AnthropicCitationCharLocationTypedDict,
)
from .anthropiccitationcontentblocklocation import (
    AnthropicCitationContentBlockLocation,
    AnthropicCitationContentBlockLocationTypedDict,
)
from .anthropiccitationpagelocation import (
    AnthropicCitationPageLocation,
    AnthropicCitationPageLocationTypedDict,
)
from .anthropiccitationsearchresultlocation import (
    AnthropicCitationSearchResultLocation,
    AnthropicCitationSearchResultLocationTypedDict,
)
from .anthropiccitationwebsearchresultlocation import (
    AnthropicCitationWebSearchResultLocation,
    AnthropicCitationWebSearchResultLocationTypedDict,
)
from functools import partial
from openrouter.types import BaseModel
from openrouter.utils.unions import parse_open_union
from pydantic import ConfigDict
from pydantic.functional_validators import BeforeValidator
from typing import Any, Literal, Union
from typing_extensions import Annotated, TypeAliasType


AnthropicTextCitationTypedDict = TypeAliasType(
    "AnthropicTextCitationTypedDict",
    Union[
        AnthropicCitationWebSearchResultLocationTypedDict,
        AnthropicCitationCharLocationTypedDict,
        AnthropicCitationPageLocationTypedDict,
        AnthropicCitationContentBlockLocationTypedDict,
        AnthropicCitationSearchResultLocationTypedDict,
    ],
)


class UnknownAnthropicTextCitation(BaseModel):
    r"""A AnthropicTextCitation variant the SDK doesn't recognize. Preserves the raw payload."""

    type: Literal["UNKNOWN"] = "UNKNOWN"
    raw: Any
    is_unknown: Literal[True] = True

    model_config = ConfigDict(frozen=True)


_ANTHROPIC_TEXT_CITATION_VARIANTS: dict[str, Any] = {
    "char_location": AnthropicCitationCharLocation,
    "content_block_location": AnthropicCitationContentBlockLocation,
    "page_location": AnthropicCitationPageLocation,
    "search_result_location": AnthropicCitationSearchResultLocation,
    "web_search_result_location": AnthropicCitationWebSearchResultLocation,
}


AnthropicTextCitation = Annotated[
    Union[
        AnthropicCitationCharLocation,
        AnthropicCitationContentBlockLocation,
        AnthropicCitationPageLocation,
        AnthropicCitationSearchResultLocation,
        AnthropicCitationWebSearchResultLocation,
        UnknownAnthropicTextCitation,
    ],
    BeforeValidator(
        partial(
            parse_open_union,
            disc_key="type",
            variants=_ANTHROPIC_TEXT_CITATION_VARIANTS,
            unknown_cls=UnknownAnthropicTextCitation,
            union_name="AnthropicTextCitation",
        )
    ),
]
