"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openrouter.types import BaseModel, UnrecognizedStr
from typing import Literal, Union
from typing_extensions import TypedDict


AnthropicBashCodeExecutionToolResultErrorErrorCode = Union[
    Literal[
        "invalid_tool_input",
        "unavailable",
        "too_many_requests",
        "execution_time_exceeded",
        "output_file_too_large",
    ],
    UnrecognizedStr,
]


AnthropicBashCodeExecutionToolResultErrorType = Literal[
    "bash_code_execution_tool_result_error",
]


class AnthropicBashCodeExecutionToolResultErrorTypedDict(TypedDict):
    error_code: AnthropicBashCodeExecutionToolResultErrorErrorCode
    type: AnthropicBashCodeExecutionToolResultErrorType


class AnthropicBashCodeExecutionToolResultError(BaseModel):
    error_code: AnthropicBashCodeExecutionToolResultErrorErrorCode

    type: AnthropicBashCodeExecutionToolResultErrorType
