"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openrouter.types import BaseModel
from typing import Literal
from typing_extensions import TypedDict


AnthropicCodeExecution20260120CallerType = Literal["code_execution_20260120",]


class AnthropicCodeExecution20260120CallerTypedDict(TypedDict):
    tool_id: str
    type: AnthropicCodeExecution20260120CallerType


class AnthropicCodeExecution20260120Caller(BaseModel):
    tool_id: str

    type: AnthropicCodeExecution20260120CallerType
