"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .anthropiccodeexecutioncontent import (
    AnthropicCodeExecutionContent,
    AnthropicCodeExecutionContentTypedDict,
)
from openrouter.types import BaseModel
from typing import Literal
from typing_extensions import TypedDict


AnthropicCodeExecutionToolResultType = Literal["code_execution_tool_result",]


class AnthropicCodeExecutionToolResultTypedDict(TypedDict):
    content: AnthropicCodeExecutionContentTypedDict
    tool_use_id: str
    type: AnthropicCodeExecutionToolResultType


class AnthropicCodeExecutionToolResult(BaseModel):
    content: AnthropicCodeExecutionContent

    tool_use_id: str

    type: AnthropicCodeExecutionToolResultType
