"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openrouter.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class AnthropicIterationCacheCreationTypedDict(TypedDict):
    ephemeral_1h_input_tokens: NotRequired[int]
    ephemeral_5m_input_tokens: NotRequired[int]


class AnthropicIterationCacheCreation(BaseModel):
    ephemeral_1h_input_tokens: Optional[int] = None

    ephemeral_5m_input_tokens: Optional[int] = None
