"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openrouter.types import BaseModel, UnrecognizedStr
from typing import Literal, Union
from typing_extensions import TypedDict


AnthropicContainerSkillType = Union[
    Literal[
        "anthropic",
        "custom",
    ],
    UnrecognizedStr,
]


class AnthropicContainerSkillTypedDict(TypedDict):
    skill_id: str
    type: AnthropicContainerSkillType
    version: str


class AnthropicContainerSkill(BaseModel):
    skill_id: str

    type: AnthropicContainerSkillType

    version: str
