"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openrouter.types import BaseModel, Nullable, UNSET_SENTINEL, UnrecognizedStr
from pydantic import model_serializer
from typing import Literal, Union
from typing_extensions import TypedDict


AnthropicRefusalStopDetailsCategory = Union[
    Literal[
        "cyber",
        "bio",
        "frontier_llm",
        "reasoning_extraction",
        "general_harms",
    ],
    UnrecognizedStr,
]


AnthropicRefusalStopDetailsType = Literal["refusal",]


class AnthropicRefusalStopDetailsTypedDict(TypedDict):
    r"""Structured information about a refusal"""

    category: Nullable[AnthropicRefusalStopDetailsCategory]
    explanation: Nullable[str]
    type: AnthropicRefusalStopDetailsType


class AnthropicRefusalStopDetails(BaseModel):
    r"""Structured information about a refusal"""

    category: Nullable[AnthropicRefusalStopDetailsCategory]

    explanation: Nullable[str]

    type: AnthropicRefusalStopDetailsType

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m
