"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .anthropictextcitation import AnthropicTextCitation, AnthropicTextCitationTypedDict
from openrouter.types import BaseModel, Nullable, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Literal
from typing_extensions import TypedDict


AnthropicTextBlockType = Literal["text",]


class AnthropicTextBlockTypedDict(TypedDict):
    citations: Nullable[List[AnthropicTextCitationTypedDict]]
    text: str
    type: AnthropicTextBlockType


class AnthropicTextBlock(BaseModel):
    citations: Nullable[List[AnthropicTextCitation]]

    text: str

    type: AnthropicTextBlockType

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m
