"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .anthropiccachecreation import (
    AnthropicCacheCreation,
    AnthropicCacheCreationTypedDict,
)
from .anthropiccontainer import AnthropicContainer, AnthropicContainerTypedDict
from .anthropicinputtransformation import (
    AnthropicInputTransformation,
    AnthropicInputTransformationTypedDict,
)
from .anthropicoutputtokensdetails import (
    AnthropicOutputTokensDetails,
    AnthropicOutputTokensDetailsTypedDict,
)
from .anthropicrefusalstopdetails import (
    AnthropicRefusalStopDetails,
    AnthropicRefusalStopDetailsTypedDict,
)
from .anthropicservertoolusage import (
    AnthropicServerToolUsage,
    AnthropicServerToolUsageTypedDict,
)
from .anthropicservicetier import AnthropicServiceTier
from .anthropicspeed import AnthropicSpeed
from .anthropicusageiteration import (
    AnthropicUsageIteration,
    AnthropicUsageIterationTypedDict,
)
from .apierrortype import APIErrorType
from .costdetails import CostDetails, CostDetailsTypedDict
from .finishreason import FinishReason
from .openresponsesresult import OpenResponsesResult, OpenResponsesResultTypedDict
from .openroutermetadata import OpenRouterMetadata, OpenRouterMetadataTypedDict
from .oranthropiccontentblock import (
    ORAnthropicContentBlock,
    ORAnthropicContentBlockTypedDict,
)
from .oranthropicstopreason import ORAnthropicStopReason
from .reasoningdetailencrypted import (
    ReasoningDetailEncrypted,
    ReasoningDetailEncryptedTypedDict,
)
from .reasoningdetailservertoolcall import (
    ReasoningDetailServerToolCall,
    ReasoningDetailServerToolCallTypedDict,
)
from .reasoningdetailsummary import (
    ReasoningDetailSummary,
    ReasoningDetailSummaryTypedDict,
)
from .reasoningdetailtext import ReasoningDetailText, ReasoningDetailTextTypedDict
from functools import partial
from openrouter.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
    UnrecognizedStr,
)
from openrouter.utils.unions import parse_open_union
import pydantic
from pydantic import ConfigDict, model_serializer
from pydantic.functional_validators import BeforeValidator
from typing import Any, Dict, List, Literal, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


BatchObjectCompletionWindow = Literal["24h",]


class BatchObjectErrorTypedDict(TypedDict):
    message: str


class BatchObjectError(BaseModel):
    message: str


BatchObjectObjectBatch = Literal["batch",]


class BatchObjectRequestCountsTypedDict(TypedDict):
    completed: int
    failed: int
    total: int


class BatchObjectRequestCounts(BaseModel):
    completed: int

    failed: int

    total: int


class ResultErrorTypedDict(TypedDict):
    message: str
    param: Nullable[str]
    type: str
    error_type: NotRequired[APIErrorType]
    r"""Canonical OpenRouter error type, stable across all API formats"""


class ResultError(BaseModel):
    message: str

    param: Nullable[str]

    type: str

    error_type: Optional[APIErrorType] = None
    r"""Canonical OpenRouter error type, stable across all API formats"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["error_type"])
        nullable_fields = set(["param"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


EmbeddingTypedDict = TypeAliasType("EmbeddingTypedDict", Union[List[float], str])
r"""Embedding vector as an array of floats or a base64 string"""


Embedding = TypeAliasType("Embedding", Union[List[float], str])
r"""Embedding vector as an array of floats or a base64 string"""


ObjectEmbedding = Literal["embedding",]


class BatchObjectDataTypedDict(TypedDict):
    r"""A single embedding object"""

    embedding: EmbeddingTypedDict
    r"""Embedding vector as an array of floats or a base64 string"""
    object: ObjectEmbedding
    index: NotRequired[int]
    r"""Index of the embedding in the input list"""


class BatchObjectData(BaseModel):
    r"""A single embedding object"""

    embedding: Embedding
    r"""Embedding vector as an array of floats or a base64 string"""

    object: ObjectEmbedding

    index: Optional[int] = None
    r"""Index of the embedding in the input list"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["index"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


BodyObjectList = Literal["list",]


class BodyPromptTokensDetails2TypedDict(TypedDict):
    r"""Per-modality token breakdown. Only present when the input contains 2+ modalities (e.g. text + image) and the upstream provider returns modality-level usage data. Only non-zero modality counts are included."""

    audio_tokens: NotRequired[int]
    r"""Number of audio tokens in the input"""
    file_tokens: NotRequired[int]
    r"""Number of file/document tokens in the input"""
    image_tokens: NotRequired[int]
    r"""Number of image tokens in the input"""
    text_tokens: NotRequired[int]
    r"""Number of text tokens in the input"""
    video_tokens: NotRequired[int]
    r"""Number of video tokens in the input"""


class BodyPromptTokensDetails2(BaseModel):
    r"""Per-modality token breakdown. Only present when the input contains 2+ modalities (e.g. text + image) and the upstream provider returns modality-level usage data. Only non-zero modality counts are included."""

    audio_tokens: Optional[int] = None
    r"""Number of audio tokens in the input"""

    file_tokens: Optional[int] = None
    r"""Number of file/document tokens in the input"""

    image_tokens: Optional[int] = None
    r"""Number of image tokens in the input"""

    text_tokens: Optional[int] = None
    r"""Number of text tokens in the input"""

    video_tokens: Optional[int] = None
    r"""Number of video tokens in the input"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "audio_tokens",
                "file_tokens",
                "image_tokens",
                "text_tokens",
                "video_tokens",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class BodyUsage3TypedDict(TypedDict):
    r"""Token usage statistics"""

    prompt_tokens: int
    r"""Number of tokens in the input"""
    total_tokens: int
    r"""Total number of tokens used"""
    cost: NotRequired[float]
    r"""Cost of the request in credits"""
    cost_details: NotRequired[Nullable[CostDetailsTypedDict]]
    r"""Breakdown of upstream inference costs"""
    is_byok: NotRequired[bool]
    r"""Whether a request was made using a Bring Your Own Key configuration"""
    prompt_tokens_details: NotRequired[BodyPromptTokensDetails2TypedDict]
    r"""Per-modality token breakdown. Only present when the input contains 2+ modalities (e.g. text + image) and the upstream provider returns modality-level usage data. Only non-zero modality counts are included."""


class BodyUsage3(BaseModel):
    r"""Token usage statistics"""

    prompt_tokens: int
    r"""Number of tokens in the input"""

    total_tokens: int
    r"""Total number of tokens used"""

    cost: Optional[float] = None
    r"""Cost of the request in credits"""

    cost_details: OptionalNullable[CostDetails] = UNSET
    r"""Breakdown of upstream inference costs"""

    is_byok: Optional[bool] = None
    r"""Whether a request was made using a Bring Your Own Key configuration"""

    prompt_tokens_details: Optional[BodyPromptTokensDetails2] = None
    r"""Per-modality token breakdown. Only present when the input contains 2+ modalities (e.g. text + image) and the upstream provider returns modality-level usage data. Only non-zero modality counts are included."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["cost", "cost_details", "is_byok", "prompt_tokens_details"]
        )
        nullable_fields = set(["cost_details"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class BodyListTypedDict(TypedDict):
    r"""Embeddings response containing embedding vectors"""

    data: List[BatchObjectDataTypedDict]
    r"""List of embedding objects"""
    model: str
    r"""The model used for embeddings"""
    object: BodyObjectList
    id: NotRequired[str]
    r"""Unique identifier for the embeddings response"""
    usage: NotRequired[BodyUsage3TypedDict]
    r"""Token usage statistics"""


class BodyList(BaseModel):
    r"""Embeddings response containing embedding vectors"""

    data: List[BatchObjectData]
    r"""List of embedding objects"""

    model: str
    r"""The model used for embeddings"""

    object: BodyObjectList

    id: Optional[str] = None
    r"""Unique identifier for the embeddings response"""

    usage: Optional[BodyUsage3] = None
    r"""Token usage statistics"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "usage"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


BatchObjectRole = Literal["assistant",]


BatchObjectTypeMessage = Literal["message",]


class BodyUsage2TypedDict(TypedDict):
    cache_creation: Nullable[AnthropicCacheCreationTypedDict]
    cache_creation_input_tokens: Nullable[int]
    cache_read_input_tokens: Nullable[int]
    inference_geo: Nullable[str]
    input_tokens: int
    output_tokens: int
    output_tokens_details: Nullable[AnthropicOutputTokensDetailsTypedDict]
    server_tool_use: Nullable[AnthropicServerToolUsageTypedDict]
    service_tier: Nullable[AnthropicServiceTier]
    iterations: NotRequired[List[AnthropicUsageIterationTypedDict]]
    speed: NotRequired[Nullable[AnthropicSpeed]]


class BodyUsage2(BaseModel):
    cache_creation: Nullable[AnthropicCacheCreation]

    cache_creation_input_tokens: Nullable[int]

    cache_read_input_tokens: Nullable[int]

    inference_geo: Nullable[str]

    input_tokens: int

    output_tokens: int

    output_tokens_details: Nullable[AnthropicOutputTokensDetails]

    server_tool_use: Nullable[AnthropicServerToolUsage]

    service_tier: Nullable[AnthropicServiceTier]

    iterations: Optional[List[AnthropicUsageIteration]] = None

    speed: OptionalNullable[AnthropicSpeed] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["iterations", "speed"])
        nullable_fields = set(
            [
                "cache_creation",
                "cache_creation_input_tokens",
                "cache_read_input_tokens",
                "inference_geo",
                "output_tokens_details",
                "server_tool_use",
                "service_tier",
                "speed",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class BodyMessageTypedDict(TypedDict):
    container: Nullable[AnthropicContainerTypedDict]
    content: List[ORAnthropicContentBlockTypedDict]
    id: str
    model: str
    role: BatchObjectRole
    stop_details: Nullable[AnthropicRefusalStopDetailsTypedDict]
    r"""Structured information about a refusal"""
    stop_reason: Nullable[ORAnthropicStopReason]
    stop_sequence: Nullable[str]
    type: BatchObjectTypeMessage
    usage: BodyUsage2TypedDict
    input_transformations: NotRequired[
        Nullable[List[AnthropicInputTransformationTypedDict]]
    ]


class BodyMessage(BaseModel):
    container: Nullable[AnthropicContainer]

    content: List[ORAnthropicContentBlock]

    id: str

    model: str

    role: BatchObjectRole

    stop_details: Nullable[AnthropicRefusalStopDetails]
    r"""Structured information about a refusal"""

    stop_reason: Nullable[ORAnthropicStopReason]

    stop_sequence: Nullable[str]

    type: BatchObjectTypeMessage

    usage: BodyUsage2

    input_transformations: OptionalNullable[List[AnthropicInputTransformation]] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["input_transformations"])
        nullable_fields = set(
            [
                "container",
                "input_transformations",
                "stop_details",
                "stop_reason",
                "stop_sequence",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class ContentTopLogprobTypedDict(TypedDict):
    bytes_: Nullable[List[int]]
    logprob: float
    token: str


class ContentTopLogprob(BaseModel):
    bytes_: Annotated[Nullable[List[int]], pydantic.Field(alias="bytes")]

    logprob: float

    token: str

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


class LogprobsContentTypedDict(TypedDict):
    bytes_: Nullable[List[int]]
    logprob: float
    token: str
    top_logprobs: List[ContentTopLogprobTypedDict]


class LogprobsContent(BaseModel):
    bytes_: Annotated[Nullable[List[int]], pydantic.Field(alias="bytes")]

    logprob: float

    token: str

    top_logprobs: List[ContentTopLogprob]

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


class RefusalTopLogprobTypedDict(TypedDict):
    bytes_: Nullable[List[int]]
    logprob: float
    token: str


class RefusalTopLogprob(BaseModel):
    bytes_: Annotated[Nullable[List[int]], pydantic.Field(alias="bytes")]

    logprob: float

    token: str

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


class RefusalTypedDict(TypedDict):
    bytes_: Nullable[List[int]]
    logprob: float
    token: str
    top_logprobs: List[RefusalTopLogprobTypedDict]


class Refusal(BaseModel):
    bytes_: Annotated[Nullable[List[int]], pydantic.Field(alias="bytes")]

    logprob: float

    token: str

    top_logprobs: List[RefusalTopLogprob]

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


class LogprobsTypedDict(TypedDict):
    content: Nullable[List[LogprobsContentTypedDict]]
    refusal: NotRequired[Nullable[List[RefusalTypedDict]]]


class Logprobs(BaseModel):
    content: Nullable[List[LogprobsContent]]

    refusal: OptionalNullable[List[Refusal]] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["refusal"])
        nullable_fields = set(["content", "refusal"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


TypeWebSearchCitation = Literal["web_search_citation",]


class WebSearchCitationTypedDict(TypedDict):
    title: Nullable[str]
    url: str
    cited_text: NotRequired[str]
    encrypted_index: NotRequired[str]


class WebSearchCitation(BaseModel):
    title: Nullable[str]

    url: str

    cited_text: Optional[str] = None

    encrypted_index: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["cited_text", "encrypted_index"])
        nullable_fields = set(["title"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class AnnotationWebSearchCitationTypedDict(TypedDict):
    type: TypeWebSearchCitation
    web_search_citation: WebSearchCitationTypedDict


class AnnotationWebSearchCitation(BaseModel):
    type: TypeWebSearchCitation

    web_search_citation: WebSearchCitation


AnnotationTypeURLCitation = Literal["url_citation",]


class BatchObjectURLCitationTypedDict(TypedDict):
    end_index: int
    start_index: int
    title: str
    url: str
    content: NotRequired[str]


class BatchObjectURLCitation(BaseModel):
    end_index: int

    start_index: int

    title: str

    url: str

    content: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["content"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class AnnotationURLCitationTypedDict(TypedDict):
    type: AnnotationTypeURLCitation
    url_citation: BatchObjectURLCitationTypedDict


class AnnotationURLCitation(BaseModel):
    type: AnnotationTypeURLCitation

    url_citation: BatchObjectURLCitation


class ContentImageURLImageURLTypedDict(TypedDict):
    url: str


class ContentImageURLImageURL(BaseModel):
    url: str


FileTypeImageURL = Literal["image_url",]


class ContentImageURLTypedDict(TypedDict):
    image_url: ContentImageURLImageURLTypedDict
    type: FileTypeImageURL


class ContentImageURL(BaseModel):
    image_url: ContentImageURLImageURL

    type: FileTypeImageURL


FileTypeText = Literal["text",]


class ContentTextTypedDict(TypedDict):
    text: str
    type: FileTypeText


class ContentText(BaseModel):
    text: str

    type: FileTypeText


AnnotationContentUnionTypedDict = TypeAliasType(
    "AnnotationContentUnionTypedDict",
    Union[ContentTextTypedDict, ContentImageURLTypedDict],
)


class UnknownAnnotationContentUnion(BaseModel):
    r"""A AnnotationContentUnion variant the SDK doesn't recognize. Preserves the raw payload."""

    type: Literal["UNKNOWN"] = "UNKNOWN"
    raw: Any
    is_unknown: Literal[True] = True

    model_config = ConfigDict(frozen=True)


_ANNOTATION_CONTENT_UNION_VARIANTS: dict[str, Any] = {
    "text": ContentText,
    "image_url": ContentImageURL,
}


AnnotationContentUnion = Annotated[
    Union[ContentText, ContentImageURL, UnknownAnnotationContentUnion],
    BeforeValidator(
        partial(
            parse_open_union,
            disc_key="type",
            variants=_ANNOTATION_CONTENT_UNION_VARIANTS,
            unknown_cls=UnknownAnnotationContentUnion,
            union_name="AnnotationContentUnion",
        )
    ),
]


class BatchObjectFileTypedDict(TypedDict):
    content: List[AnnotationContentUnionTypedDict]
    hash: str
    name: NotRequired[str]


class BatchObjectFile(BaseModel):
    content: List[AnnotationContentUnion]

    hash: str

    name: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["name"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


AnnotationTypeFile = Literal["file",]


class AnnotationFileTypedDict(TypedDict):
    file: BatchObjectFileTypedDict
    type: AnnotationTypeFile


class AnnotationFile(BaseModel):
    file: BatchObjectFile

    type: AnnotationTypeFile


AnnotationTypedDict = TypeAliasType(
    "AnnotationTypedDict",
    Union[
        AnnotationFileTypedDict,
        AnnotationURLCitationTypedDict,
        AnnotationWebSearchCitationTypedDict,
    ],
)


class UnknownAnnotation(BaseModel):
    r"""A Annotation variant the SDK doesn't recognize. Preserves the raw payload."""

    type: Literal["UNKNOWN"] = "UNKNOWN"
    raw: Any
    is_unknown: Literal[True] = True

    model_config = ConfigDict(frozen=True)


_ANNOTATION_VARIANTS: dict[str, Any] = {
    "file": AnnotationFile,
    "url_citation": AnnotationURLCitation,
    "web_search_citation": AnnotationWebSearchCitation,
}


Annotation = Annotated[
    Union[
        AnnotationFile,
        AnnotationURLCitation,
        AnnotationWebSearchCitation,
        UnknownAnnotation,
    ],
    BeforeValidator(
        partial(
            parse_open_union,
            disc_key="type",
            variants=_ANNOTATION_VARIANTS,
            unknown_cls=UnknownAnnotation,
            union_name="Annotation",
        )
    ),
]


class BatchObjectImageURLTypedDict(TypedDict):
    url: str


class BatchObjectImageURL(BaseModel):
    url: str


ChoiceTypeImageURL = Literal["image_url",]


class ImageTypedDict(TypedDict):
    image_url: BatchObjectImageURLTypedDict
    type: ChoiceTypeImageURL


class Image(BaseModel):
    image_url: BatchObjectImageURL

    type: ChoiceTypeImageURL


ReasoningDetailTypedDict = TypeAliasType(
    "ReasoningDetailTypedDict",
    Union[
        ReasoningDetailSummaryTypedDict,
        ReasoningDetailEncryptedTypedDict,
        ReasoningDetailTextTypedDict,
        ReasoningDetailServerToolCallTypedDict,
    ],
)


class UnknownReasoningDetail(BaseModel):
    r"""A ReasoningDetail variant the SDK doesn't recognize. Preserves the raw payload."""

    type: Literal["UNKNOWN"] = "UNKNOWN"
    raw: Any
    is_unknown: Literal[True] = True

    model_config = ConfigDict(frozen=True)


_REASONING_DETAIL_VARIANTS: dict[str, Any] = {
    "reasoning.summary": ReasoningDetailSummary,
    "reasoning.encrypted": ReasoningDetailEncrypted,
    "reasoning.text": ReasoningDetailText,
    "reasoning.server_tool_call": ReasoningDetailServerToolCall,
}


ReasoningDetail = Annotated[
    Union[
        ReasoningDetailSummary,
        ReasoningDetailEncrypted,
        ReasoningDetailText,
        ReasoningDetailServerToolCall,
        UnknownReasoningDetail,
    ],
    BeforeValidator(
        partial(
            parse_open_union,
            disc_key="type",
            variants=_REASONING_DETAIL_VARIANTS,
            unknown_cls=UnknownReasoningDetail,
            union_name="ReasoningDetail",
        )
    ),
]


ChoiceRole = Literal["assistant",]


class BatchObjectFunctionTypedDict(TypedDict):
    arguments: str
    name: str


class BatchObjectFunction(BaseModel):
    arguments: str

    name: str


ChoiceTypeFunction = Literal["function",]


class ToolCallTypedDict(TypedDict):
    function: BatchObjectFunctionTypedDict
    id: str
    index: int
    type: ChoiceTypeFunction


class ToolCall(BaseModel):
    function: BatchObjectFunction

    id: str

    index: int

    type: ChoiceTypeFunction


class MessageTypedDict(TypedDict):
    content: Nullable[str]
    refusal: Nullable[str]
    role: ChoiceRole
    annotations: NotRequired[List[AnnotationTypedDict]]
    images: NotRequired[Nullable[List[ImageTypedDict]]]
    reasoning: NotRequired[Nullable[str]]
    reasoning_details: NotRequired[Nullable[List[Nullable[ReasoningDetailTypedDict]]]]
    tool_calls: NotRequired[List[ToolCallTypedDict]]


class Message(BaseModel):
    content: Nullable[str]

    refusal: Nullable[str]

    role: ChoiceRole

    annotations: Optional[List[Annotation]] = None

    images: OptionalNullable[List[Image]] = UNSET

    reasoning: OptionalNullable[str] = UNSET

    reasoning_details: OptionalNullable[List[Nullable[ReasoningDetail]]] = UNSET

    tool_calls: Optional[List[ToolCall]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["annotations", "images", "reasoning", "reasoning_details", "tool_calls"]
        )
        nullable_fields = set(
            ["content", "images", "reasoning", "reasoning_details", "refusal"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class ChoiceTypedDict(TypedDict):
    finish_reason: FinishReason
    index: int
    logprobs: Nullable[LogprobsTypedDict]
    message: MessageTypedDict
    native_finish_reason: Nullable[str]


class Choice(BaseModel):
    finish_reason: FinishReason

    index: int

    logprobs: Nullable[Logprobs]

    message: Message

    native_finish_reason: Nullable[str]

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


BatchObjectEvent = Union[
    Literal[
        "adapter_request",
        "upstream_headers_received",
        "first_token_received",
        "upstream_body_ended",
    ],
    UnrecognizedStr,
]


class BatchObjectTimingsTypedDict(TypedDict):
    epoch_ms: int
    event: BatchObjectEvent
    start_ms: int


class BatchObjectTimings(BaseModel):
    epoch_ms: int

    event: BatchObjectEvent

    start_ms: int


class BatchObjectDebugTypedDict(TypedDict):
    echo_upstream_body: NotRequired[Dict[str, Any]]
    timings: NotRequired[BatchObjectTimingsTypedDict]


class BatchObjectDebug(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True, arbitrary_types_allowed=True, extra="allow"
    )
    __pydantic_extra__: Dict[str, Any] = pydantic.Field(init=False)

    echo_upstream_body: Optional[Dict[str, Any]] = None

    timings: Optional[BatchObjectTimings] = None

    @property
    def additional_properties(self):
        return self.__pydantic_extra__

    @additional_properties.setter
    def additional_properties(self, value):
        self.__pydantic_extra__ = value  # pyright: ignore[reportIncompatibleVariableOverride]

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["echo_upstream_body", "timings"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            serialized.pop(k, serialized.pop(n, None))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val
        for k, v in serialized.items():
            m[k] = v

        return m


BodyObjectChatCompletion = Literal["chat.completion",]


class BodyCompletionTokensDetailsTypedDict(TypedDict):
    audio_tokens: NotRequired[Nullable[int]]
    r"""Tokens generated by the model for audio output."""
    image_tokens: NotRequired[Nullable[int]]
    r"""Tokens generated by the model for image output."""
    reasoning_tokens: NotRequired[Nullable[int]]
    r"""Tokens generated by the model for reasoning."""


class BodyCompletionTokensDetails(BaseModel):
    audio_tokens: OptionalNullable[int] = UNSET
    r"""Tokens generated by the model for audio output."""

    image_tokens: OptionalNullable[int] = UNSET
    r"""Tokens generated by the model for image output."""

    reasoning_tokens: OptionalNullable[int] = UNSET
    r"""Tokens generated by the model for reasoning."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["audio_tokens", "image_tokens", "reasoning_tokens"])
        nullable_fields = set(["audio_tokens", "image_tokens", "reasoning_tokens"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class BodyPromptTokensDetails1TypedDict(TypedDict):
    r"""Breakdown of tokens used in the prompt."""

    audio_tokens: NotRequired[Nullable[int]]
    r"""Tokens used for input audio."""
    cache_write_tokens: NotRequired[Nullable[int]]
    r"""Tokens written to cache. Only returned for models with explicit caching and cache write pricing."""
    cached_tokens: NotRequired[Nullable[int]]
    r"""Tokens cached by the endpoint."""
    file_tokens: NotRequired[Nullable[int]]
    r"""Tokens used for input files/documents."""
    video_tokens: NotRequired[Nullable[int]]
    r"""Tokens used for input video."""


class BodyPromptTokensDetails1(BaseModel):
    r"""Breakdown of tokens used in the prompt."""

    audio_tokens: OptionalNullable[int] = UNSET
    r"""Tokens used for input audio."""

    cache_write_tokens: OptionalNullable[int] = UNSET
    r"""Tokens written to cache. Only returned for models with explicit caching and cache write pricing."""

    cached_tokens: OptionalNullable[int] = UNSET
    r"""Tokens cached by the endpoint."""

    file_tokens: OptionalNullable[int] = UNSET
    r"""Tokens used for input files/documents."""

    video_tokens: OptionalNullable[int] = UNSET
    r"""Tokens used for input video."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "audio_tokens",
                "cache_write_tokens",
                "cached_tokens",
                "file_tokens",
                "video_tokens",
            ]
        )
        nullable_fields = set(
            [
                "audio_tokens",
                "cache_write_tokens",
                "cached_tokens",
                "file_tokens",
                "video_tokens",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class BodyServerToolUseTypedDict(TypedDict):
    r"""Usage for server-side tool execution (e.g., web search)"""

    tool_calls_executed: NotRequired[Nullable[int]]
    r"""Number of OpenRouter server tool calls that executed and produced a result."""
    tool_calls_requested: NotRequired[Nullable[int]]
    r"""Total number of OpenRouter server-orchestrated tool calls the model requested, across all tool types. Provider-native tools (e.g. native web search) are not counted here."""
    web_search_requests: NotRequired[Nullable[int]]
    r"""Number of web searches performed by server-side tools. For server-orchestrated tool calls a web search is also counted in tool_calls_requested; provider-native web search may report web_search_requests only. Do not sum the two."""


class BodyServerToolUse(BaseModel):
    r"""Usage for server-side tool execution (e.g., web search)"""

    tool_calls_executed: OptionalNullable[int] = UNSET
    r"""Number of OpenRouter server tool calls that executed and produced a result."""

    tool_calls_requested: OptionalNullable[int] = UNSET
    r"""Total number of OpenRouter server-orchestrated tool calls the model requested, across all tool types. Provider-native tools (e.g. native web search) are not counted here."""

    web_search_requests: OptionalNullable[int] = UNSET
    r"""Number of web searches performed by server-side tools. For server-orchestrated tool calls a web search is also counted in tool_calls_requested; provider-native web search may report web_search_requests only. Do not sum the two."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["tool_calls_executed", "tool_calls_requested", "web_search_requests"]
        )
        nullable_fields = set(
            ["tool_calls_executed", "tool_calls_requested", "web_search_requests"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class BatchObjectServerToolUseDetailsTypedDict(TypedDict):
    r"""Usage for server-side tool execution (e.g., web search)"""

    tool_calls_executed: NotRequired[Nullable[int]]
    r"""Number of OpenRouter server tool calls that executed and produced a result."""
    tool_calls_requested: NotRequired[Nullable[int]]
    r"""Total number of OpenRouter server-orchestrated tool calls the model requested, across all tool types. Provider-native tools (e.g. native web search) are not counted here."""
    web_search_requests: NotRequired[Nullable[int]]
    r"""Number of web searches performed by server-side tools. For server-orchestrated tool calls a web search is also counted in tool_calls_requested; provider-native web search may report web_search_requests only. Do not sum the two."""


class BatchObjectServerToolUseDetails(BaseModel):
    r"""Usage for server-side tool execution (e.g., web search)"""

    tool_calls_executed: OptionalNullable[int] = UNSET
    r"""Number of OpenRouter server tool calls that executed and produced a result."""

    tool_calls_requested: OptionalNullable[int] = UNSET
    r"""Total number of OpenRouter server-orchestrated tool calls the model requested, across all tool types. Provider-native tools (e.g. native web search) are not counted here."""

    web_search_requests: OptionalNullable[int] = UNSET
    r"""Number of web searches performed by server-side tools. For server-orchestrated tool calls a web search is also counted in tool_calls_requested; provider-native web search may report web_search_requests only. Do not sum the two."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["tool_calls_executed", "tool_calls_requested", "web_search_requests"]
        )
        nullable_fields = set(
            ["tool_calls_executed", "tool_calls_requested", "web_search_requests"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class BodyUsage1TypedDict(TypedDict):
    completion_tokens: int
    r"""The tokens generated"""
    prompt_tokens: int
    r"""Including images, input audio, and tools if any"""
    total_tokens: int
    r"""Sum of the above two fields"""
    completion_tokens_details: NotRequired[
        Nullable[BodyCompletionTokensDetailsTypedDict]
    ]
    prompt_tokens_details: NotRequired[Nullable[BodyPromptTokensDetails1TypedDict]]
    r"""Breakdown of tokens used in the prompt."""
    server_tool_use: NotRequired[Nullable[BodyServerToolUseTypedDict]]
    r"""Usage for server-side tool execution (e.g., web search)"""
    server_tool_use_details: NotRequired[
        Nullable[BatchObjectServerToolUseDetailsTypedDict]
    ]
    r"""Usage for server-side tool execution (e.g., web search)"""


class BodyUsage1(BaseModel):
    completion_tokens: int
    r"""The tokens generated"""

    prompt_tokens: int
    r"""Including images, input audio, and tools if any"""

    total_tokens: int
    r"""Sum of the above two fields"""

    completion_tokens_details: OptionalNullable[BodyCompletionTokensDetails] = UNSET

    prompt_tokens_details: OptionalNullable[BodyPromptTokensDetails1] = UNSET
    r"""Breakdown of tokens used in the prompt."""

    server_tool_use: OptionalNullable[BodyServerToolUse] = UNSET
    r"""Usage for server-side tool execution (e.g., web search)"""

    server_tool_use_details: OptionalNullable[BatchObjectServerToolUseDetails] = UNSET
    r"""Usage for server-side tool execution (e.g., web search)"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "completion_tokens_details",
                "prompt_tokens_details",
                "server_tool_use",
                "server_tool_use_details",
            ]
        )
        nullable_fields = set(
            [
                "completion_tokens_details",
                "prompt_tokens_details",
                "server_tool_use",
                "server_tool_use_details",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class BodyChatCompletionTypedDict(TypedDict):
    choices: List[ChoiceTypedDict]
    created: int
    id: str
    model: str
    object: BodyObjectChatCompletion
    debug: NotRequired[BatchObjectDebugTypedDict]
    openrouter_metadata: NotRequired[OpenRouterMetadataTypedDict]
    provider: NotRequired[Nullable[str]]
    service_tier: NotRequired[Nullable[str]]
    system_fingerprint: NotRequired[Nullable[str]]
    usage: NotRequired[BodyUsage1TypedDict]


class BodyChatCompletion(BaseModel):
    choices: List[Choice]

    created: int

    id: str

    model: str

    object: BodyObjectChatCompletion

    debug: Optional[BatchObjectDebug] = None

    openrouter_metadata: Optional[OpenRouterMetadata] = None

    provider: OptionalNullable[str] = UNSET

    service_tier: OptionalNullable[str] = UNSET

    system_fingerprint: OptionalNullable[str] = UNSET

    usage: Optional[BodyUsage1] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "debug",
                "openrouter_metadata",
                "provider",
                "service_tier",
                "system_fingerprint",
                "usage",
            ]
        )
        nullable_fields = set(["provider", "service_tier", "system_fingerprint"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


BodyTypedDict = TypeAliasType(
    "BodyTypedDict",
    Union[
        BodyListTypedDict,
        BodyChatCompletionTypedDict,
        BodyMessageTypedDict,
        OpenResponsesResultTypedDict,
    ],
)


Body = TypeAliasType(
    "Body", Union[BodyList, BodyChatCompletion, BodyMessage, OpenResponsesResult]
)


class BatchObjectResponseTypedDict(TypedDict):
    body: BodyTypedDict
    request_id: Nullable[str]
    status_code: int


class BatchObjectResponse(BaseModel):
    body: Body

    request_id: Nullable[str]

    status_code: int

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


class ResultTypedDict(TypedDict):
    custom_id: str
    error: Nullable[ResultErrorTypedDict]
    id: str
    response: Nullable[BatchObjectResponseTypedDict]


class Result(BaseModel):
    custom_id: str

    error: Nullable[ResultError]

    id: str

    response: Nullable[BatchObjectResponse]

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


BatchObjectStatus = Union[
    Literal[
        "validating",
        "in_progress",
        "finalizing",
        "completed",
        "failed",
        "expired",
        "cancelling",
        "cancelled",
    ],
    UnrecognizedStr,
]


class BatchObjectCompletionTokensDetailsTypedDict(TypedDict):
    audio_tokens: NotRequired[Nullable[int]]
    r"""Tokens generated by the model for audio output."""
    image_tokens: NotRequired[Nullable[int]]
    r"""Tokens generated by the model for image output."""
    reasoning_tokens: NotRequired[Nullable[int]]
    r"""Tokens generated by the model for reasoning."""


class BatchObjectCompletionTokensDetails(BaseModel):
    audio_tokens: OptionalNullable[int] = UNSET
    r"""Tokens generated by the model for audio output."""

    image_tokens: OptionalNullable[int] = UNSET
    r"""Tokens generated by the model for image output."""

    reasoning_tokens: OptionalNullable[int] = UNSET
    r"""Tokens generated by the model for reasoning."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["audio_tokens", "image_tokens", "reasoning_tokens"])
        nullable_fields = set(["audio_tokens", "image_tokens", "reasoning_tokens"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class BatchObjectPromptTokensDetailsTypedDict(TypedDict):
    r"""Breakdown of tokens used in the prompt."""

    audio_tokens: NotRequired[Nullable[int]]
    r"""Tokens used for input audio."""
    cache_write_tokens: NotRequired[Nullable[int]]
    r"""Tokens written to cache. Only returned for models with explicit caching and cache write pricing."""
    cached_tokens: NotRequired[Nullable[int]]
    r"""Tokens cached by the endpoint."""
    file_tokens: NotRequired[Nullable[int]]
    r"""Tokens used for input files/documents."""
    video_tokens: NotRequired[Nullable[int]]
    r"""Tokens used for input video."""


class BatchObjectPromptTokensDetails(BaseModel):
    r"""Breakdown of tokens used in the prompt."""

    audio_tokens: OptionalNullable[int] = UNSET
    r"""Tokens used for input audio."""

    cache_write_tokens: OptionalNullable[int] = UNSET
    r"""Tokens written to cache. Only returned for models with explicit caching and cache write pricing."""

    cached_tokens: OptionalNullable[int] = UNSET
    r"""Tokens cached by the endpoint."""

    file_tokens: OptionalNullable[int] = UNSET
    r"""Tokens used for input files/documents."""

    video_tokens: OptionalNullable[int] = UNSET
    r"""Tokens used for input video."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "audio_tokens",
                "cache_write_tokens",
                "cached_tokens",
                "file_tokens",
                "video_tokens",
            ]
        )
        nullable_fields = set(
            [
                "audio_tokens",
                "cache_write_tokens",
                "cached_tokens",
                "file_tokens",
                "video_tokens",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class BatchObjectServerToolUseTypedDict(TypedDict):
    r"""Usage for server-side tool execution (e.g., web search)"""

    tool_calls_executed: NotRequired[Nullable[int]]
    r"""Number of OpenRouter server tool calls that executed and produced a result."""
    tool_calls_requested: NotRequired[Nullable[int]]
    r"""Total number of OpenRouter server-orchestrated tool calls the model requested, across all tool types. Provider-native tools (e.g. native web search) are not counted here."""
    web_search_requests: NotRequired[Nullable[int]]
    r"""Number of web searches performed by server-side tools. For server-orchestrated tool calls a web search is also counted in tool_calls_requested; provider-native web search may report web_search_requests only. Do not sum the two."""


class BatchObjectServerToolUse(BaseModel):
    r"""Usage for server-side tool execution (e.g., web search)"""

    tool_calls_executed: OptionalNullable[int] = UNSET
    r"""Number of OpenRouter server tool calls that executed and produced a result."""

    tool_calls_requested: OptionalNullable[int] = UNSET
    r"""Total number of OpenRouter server-orchestrated tool calls the model requested, across all tool types. Provider-native tools (e.g. native web search) are not counted here."""

    web_search_requests: OptionalNullable[int] = UNSET
    r"""Number of web searches performed by server-side tools. For server-orchestrated tool calls a web search is also counted in tool_calls_requested; provider-native web search may report web_search_requests only. Do not sum the two."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["tool_calls_executed", "tool_calls_requested", "web_search_requests"]
        )
        nullable_fields = set(
            ["tool_calls_executed", "tool_calls_requested", "web_search_requests"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class BatchObjectUsageTypedDict(TypedDict):
    completion_tokens: int
    r"""The tokens generated"""
    prompt_tokens: int
    r"""Including images, input audio, and tools if any"""
    total_tokens: int
    r"""Sum of the above two fields"""
    cache_creation: NotRequired[Nullable[AnthropicCacheCreationTypedDict]]
    completion_tokens_details: NotRequired[
        Nullable[BatchObjectCompletionTokensDetailsTypedDict]
    ]
    cost: NotRequired[Nullable[float]]
    r"""Cost of the completion"""
    cost_details: NotRequired[Nullable[CostDetailsTypedDict]]
    r"""Breakdown of upstream inference costs"""
    is_byok: NotRequired[bool]
    r"""Whether a request was made using a Bring Your Own Key configuration"""
    iterations: NotRequired[Nullable[List[AnthropicUsageIterationTypedDict]]]
    prompt_tokens_details: NotRequired[
        Nullable[BatchObjectPromptTokensDetailsTypedDict]
    ]
    r"""Breakdown of tokens used in the prompt."""
    server_tool_use: NotRequired[Nullable[BatchObjectServerToolUseTypedDict]]
    r"""Usage for server-side tool execution (e.g., web search)"""
    service_tier: NotRequired[Nullable[str]]
    r"""The service tier used by the upstream provider for this request"""
    speed: NotRequired[Nullable[AnthropicSpeed]]


class BatchObjectUsage(BaseModel):
    completion_tokens: int
    r"""The tokens generated"""

    prompt_tokens: int
    r"""Including images, input audio, and tools if any"""

    total_tokens: int
    r"""Sum of the above two fields"""

    cache_creation: OptionalNullable[AnthropicCacheCreation] = UNSET

    completion_tokens_details: OptionalNullable[BatchObjectCompletionTokensDetails] = (
        UNSET
    )

    cost: OptionalNullable[float] = UNSET
    r"""Cost of the completion"""

    cost_details: OptionalNullable[CostDetails] = UNSET
    r"""Breakdown of upstream inference costs"""

    is_byok: Optional[bool] = None
    r"""Whether a request was made using a Bring Your Own Key configuration"""

    iterations: OptionalNullable[List[AnthropicUsageIteration]] = UNSET

    prompt_tokens_details: OptionalNullable[BatchObjectPromptTokensDetails] = UNSET
    r"""Breakdown of tokens used in the prompt."""

    server_tool_use: OptionalNullable[BatchObjectServerToolUse] = UNSET
    r"""Usage for server-side tool execution (e.g., web search)"""

    service_tier: OptionalNullable[str] = UNSET
    r"""The service tier used by the upstream provider for this request"""

    speed: OptionalNullable[AnthropicSpeed] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "cache_creation",
                "completion_tokens_details",
                "cost",
                "cost_details",
                "is_byok",
                "iterations",
                "prompt_tokens_details",
                "server_tool_use",
                "service_tier",
                "speed",
            ]
        )
        nullable_fields = set(
            [
                "cache_creation",
                "completion_tokens_details",
                "cost",
                "cost_details",
                "iterations",
                "prompt_tokens_details",
                "server_tool_use",
                "service_tier",
                "speed",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class BatchObjectTypedDict(TypedDict):
    completion_window: BatchObjectCompletionWindow
    created_at: int
    endpoint: str
    error: Nullable[BatchObjectErrorTypedDict]
    finalized_at: Nullable[int]
    id: str
    model: str
    object: BatchObjectObjectBatch
    request_counts: BatchObjectRequestCountsTypedDict
    results: Nullable[List[ResultTypedDict]]
    status: BatchObjectStatus
    usage: Nullable[BatchObjectUsageTypedDict]


class BatchObject(BaseModel):
    completion_window: BatchObjectCompletionWindow

    created_at: int

    endpoint: str

    error: Nullable[BatchObjectError]

    finalized_at: Nullable[int]

    id: str

    model: str

    object: BatchObjectObjectBatch

    request_counts: BatchObjectRequestCounts

    results: Nullable[List[Result]]

    status: BatchObjectStatus

    usage: Nullable[BatchObjectUsage]

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


try:
    ContentTopLogprob.model_rebuild()
except NameError:
    pass
try:
    LogprobsContent.model_rebuild()
except NameError:
    pass
try:
    RefusalTopLogprob.model_rebuild()
except NameError:
    pass
try:
    Refusal.model_rebuild()
except NameError:
    pass
