"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .batchproviderpreferences import (
    BatchProviderPreferences,
    BatchProviderPreferencesTypedDict,
)
from openrouter.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
    UnrecognizedStr,
)
from pydantic import model_serializer
from typing import Any, Dict, List, Literal, Optional, Union
from typing_extensions import NotRequired, TypedDict


BatchSubmitBodyCompletionWindow = Literal["24h",]


Endpoint = Union[
    Literal[
        "/v1/chat/completions",
        "/v1/responses",
        "/v1/messages",
        "/v1/embeddings",
    ],
    UnrecognizedStr,
]


class RequestTypedDict(TypedDict):
    body: Dict[str, Any]
    r"""Request payload for the batch `endpoint`."""
    custom_id: str


class Request(BaseModel):
    body: Dict[str, Any]
    r"""Request payload for the batch `endpoint`."""

    custom_id: str


class BatchSubmitBodyTypedDict(TypedDict):
    r"""Batch submit request body."""

    endpoint: Endpoint
    model: str
    requests: List[RequestTypedDict]
    completion_window: NotRequired[BatchSubmitBodyCompletionWindow]
    provider: NotRequired[Nullable[BatchProviderPreferencesTypedDict]]
    r"""Batch provider routing preferences. Only `provider.only` is supported."""


class BatchSubmitBody(BaseModel):
    r"""Batch submit request body."""

    endpoint: Endpoint

    model: str

    requests: List[Request]

    completion_window: Optional[BatchSubmitBodyCompletionWindow] = "24h"

    provider: OptionalNullable[BatchProviderPreferences] = UNSET
    r"""Batch provider routing preferences. Only `provider.only` is supported."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["completion_window", "provider"])
        nullable_fields = set(["provider"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
