"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openrouter.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class CreateInternRequestTypedDict(TypedDict):
    r"""Settings for a new intern in an explicit workspace."""

    name: str
    r"""Intern name, unique per creator within the workspace."""
    workspace_id: str
    r"""Workspace that will own the intern. It must match the API key workspace."""
    description: NotRequired[Nullable[str]]
    r"""Free-form description, or null."""
    instructions: NotRequired[Nullable[str]]
    r"""Standing instructions the intern boots with, or null."""
    provision: NotRequired[bool]
    r"""Start provisioning during this create operation. Defaults to false."""
    vault_id: NotRequired[str]
    r"""Vault owned by another intern in this workspace to attach as a borrowed vault."""


class CreateInternRequest(BaseModel):
    r"""Settings for a new intern in an explicit workspace."""

    name: str
    r"""Intern name, unique per creator within the workspace."""

    workspace_id: str
    r"""Workspace that will own the intern. It must match the API key workspace."""

    description: OptionalNullable[str] = UNSET
    r"""Free-form description, or null."""

    instructions: OptionalNullable[str] = UNSET
    r"""Standing instructions the intern boots with, or null."""

    provision: Optional[bool] = False
    r"""Start provisioning during this create operation. Defaults to false."""

    vault_id: Optional[str] = None
    r"""Vault owned by another intern in this workspace to attach as a borrowed vault."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["description", "instructions", "provision", "vault_id"])
        nullable_fields = set(["description", "instructions"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
