"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openrouter.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Any, Dict, List, Literal, Optional, Union
from typing_extensions import NotRequired, TypeAliasType, TypedDict


LegendTypedDict = TypeAliasType(
    "LegendTypedDict", Union[str, Dict[str, Any], List[Any]]
)
r"""A plain string, or a JSON object or array of structured guidance."""


Legend = TypeAliasType("Legend", Union[str, Dict[str, Any], List[Any]])
r"""A plain string, or a JSON object or array of structured guidance."""


DecisionsScoreAnswerType = Literal["score",]


class DecisionsScoreAnswerTypedDict(TypedDict):
    score: float
    type: DecisionsScoreAnswerType
    confidence: NotRequired[float]
    legend: NotRequired[Dict[str, LegendTypedDict]]
    probabilities: NotRequired[Dict[str, float]]


class DecisionsScoreAnswer(BaseModel):
    score: float

    type: DecisionsScoreAnswerType

    confidence: Optional[float] = None

    legend: Optional[Dict[str, Legend]] = None

    probabilities: Optional[Dict[str, float]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["confidence", "legend", "probabilities"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
