"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openrouter.types import BaseModel, Nullable
from typing import Any, Dict, List, Literal, Union
from typing_extensions import TypeAliasType, TypedDict


CriteriaTypedDict = TypeAliasType(
    "CriteriaTypedDict", Union[str, Dict[str, Any], List[Any]]
)
r"""A plain string, or a JSON object or array of structured guidance."""


Criteria = TypeAliasType("Criteria", Union[str, Dict[str, Any], List[Any]])
r"""A plain string, or a JSON object or array of structured guidance."""


DecisionsChoiceQuestionInstructionsTypedDict = TypeAliasType(
    "DecisionsChoiceQuestionInstructionsTypedDict",
    Union[str, Dict[str, Any], List[Any]],
)
r"""A plain string, or a JSON object or array of structured guidance."""


DecisionsChoiceQuestionInstructions = TypeAliasType(
    "DecisionsChoiceQuestionInstructions", Union[str, Dict[str, Any], List[Any]]
)
r"""A plain string, or a JSON object or array of structured guidance."""


DecisionsChoiceQuestionType = Literal["choice",]


class DecisionsChoiceQuestionTypedDict(TypedDict):
    criteria: Dict[str, Nullable[CriteriaTypedDict]]
    instructions: DecisionsChoiceQuestionInstructionsTypedDict
    r"""A plain string, or a JSON object or array of structured guidance."""
    type: DecisionsChoiceQuestionType


class DecisionsChoiceQuestion(BaseModel):
    criteria: Dict[str, Nullable[Criteria]]

    instructions: DecisionsChoiceQuestionInstructions
    r"""A plain string, or a JSON object or array of structured guidance."""

    type: DecisionsChoiceQuestionType
