"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .decisionschoicequestion import (
    DecisionsChoiceQuestion,
    DecisionsChoiceQuestionTypedDict,
)
from .decisionsnoulquestion import DecisionsNoulQuestion, DecisionsNoulQuestionTypedDict
from .decisionsscorequestion import (
    DecisionsScoreQuestion,
    DecisionsScoreQuestionTypedDict,
)
from .providerpreferences import ProviderPreferences, ProviderPreferencesTypedDict
from .traceconfig import TraceConfig, TraceConfigTypedDict
from openrouter.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from openrouter.utils import get_discriminator
from pydantic import Discriminator, Tag, model_serializer
from typing import Any, Dict, List, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


QuestionsTypedDict = TypeAliasType(
    "QuestionsTypedDict",
    Union[
        DecisionsNoulQuestionTypedDict,
        DecisionsChoiceQuestionTypedDict,
        DecisionsScoreQuestionTypedDict,
    ],
)
r"""A Decisions question using a boolean, choice, or ordered score evaluation."""


Questions = Annotated[
    Union[
        Annotated[DecisionsChoiceQuestion, Tag("choice")],
        Annotated[DecisionsNoulQuestion, Tag("noul")],
        Annotated[DecisionsScoreQuestion, Tag("score")],
    ],
    Discriminator(lambda m: get_discriminator(m, "type", "type")),
]
r"""A Decisions question using a boolean, choice, or ordered score evaluation."""


StateTypedDict = TypeAliasType("StateTypedDict", Union[str, Dict[str, Any], List[Any]])
r"""The content to evaluate: a plain string, or a JSON object or array of related context."""


State = TypeAliasType("State", Union[str, Dict[str, Any], List[Any]])
r"""The content to evaluate: a plain string, or a JSON object or array of related context."""


class DecisionsRequestTypedDict(TypedDict):
    model: str
    questions: Dict[str, QuestionsTypedDict]
    state: StateTypedDict
    r"""The content to evaluate: a plain string, or a JSON object or array of related context."""
    provider: NotRequired[Nullable[ProviderPreferencesTypedDict]]
    session_id: NotRequired[str]
    r"""A unique identifier for grouping related requests (e.g., a conversation or agent workflow). Used for observability grouping in Broadcast and private logging; never sent to the provider. If provided in both the request body and the x-session-id header, the body value takes precedence. Maximum of 256 characters."""
    trace: NotRequired[TraceConfigTypedDict]
    r"""Metadata for observability and tracing. Known keys (trace_id, trace_name, span_name, generation_name, parent_span_id) have special handling. Additional keys are passed through as custom metadata to configured broadcast destinations."""
    user: NotRequired[str]


class DecisionsRequest(BaseModel):
    model: str

    questions: Dict[str, Questions]

    state: State
    r"""The content to evaluate: a plain string, or a JSON object or array of related context."""

    provider: OptionalNullable[ProviderPreferences] = UNSET

    session_id: Optional[str] = None
    r"""A unique identifier for grouping related requests (e.g., a conversation or agent workflow). Used for observability grouping in Broadcast and private logging; never sent to the provider. If provided in both the request body and the x-session-id header, the body value takes precedence. Maximum of 256 characters."""

    trace: Optional[TraceConfig] = None
    r"""Metadata for observability and tracing. Known keys (trace_id, trace_name, span_name, generation_name, parent_span_id) have special handling. Additional keys are passed through as custom metadata to configured broadcast destinations."""

    user: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["provider", "session_id", "trace", "user"])
        nullable_fields = set(["provider"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
