"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openrouter.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class DefaultParametersTypedDict(TypedDict):
    r"""Default parameters for this model"""

    frequency_penalty: NotRequired[float]
    presence_penalty: NotRequired[float]
    repetition_penalty: NotRequired[float]
    temperature: NotRequired[float]
    top_k: NotRequired[Nullable[int]]
    top_p: NotRequired[float]


class DefaultParameters(BaseModel):
    r"""Default parameters for this model"""

    frequency_penalty: Optional[float] = None

    presence_penalty: Optional[float] = None

    repetition_penalty: Optional[float] = None

    temperature: Optional[float] = None

    top_k: OptionalNullable[int] = UNSET

    top_p: Optional[float] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = [
            "frequency_penalty",
            "presence_penalty",
            "repetition_penalty",
            "temperature",
            "top_k",
            "top_p",
        ]
        nullable_fields = ["top_k"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
