"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .deferredtoolssearchstrategy import (
    DeferredToolsSearchStrategy,
    DeferredToolsSearchStrategyTypedDict,
)
from openrouter.types import BaseModel
from typing import Literal
from typing_extensions import TypedDict


Profile = Literal["portable",]
r"""Loading profile. Only `portable` is available in this release: OpenRouter serves deferral with router-built search and call wrappers on any model."""


Protocol = Literal["v1",]


Validation = Literal["runtime",]
r"""Where tool-call arguments are checked against the original schema. Only `runtime` (in OpenRouter) is available in this release."""


class DeferredToolsControlTypedDict(TypedDict):
    r"""Opt-in versioned router-level deferred-tool protocol. Replay assistant reasoning unchanged on continuation; keep the catalog unchanged."""

    profile: Profile
    r"""Loading profile. Only `portable` is available in this release: OpenRouter serves deferral with router-built search and call wrappers on any model."""
    protocol: Protocol
    search: DeferredToolsSearchStrategyTypedDict
    r"""Router-local regex/BM25 or caller-owned custom search."""
    validation: Validation
    r"""Where tool-call arguments are checked against the original schema. Only `runtime` (in OpenRouter) is available in this release."""


class DeferredToolsControl(BaseModel):
    r"""Opt-in versioned router-level deferred-tool protocol. Replay assistant reasoning unchanged on continuation; keep the catalog unchanged."""

    profile: Profile
    r"""Loading profile. Only `portable` is available in this release: OpenRouter serves deferral with router-built search and call wrappers on any model."""

    protocol: Protocol

    search: DeferredToolsSearchStrategy
    r"""Router-local regex/BM25 or caller-owned custom search."""

    validation: Validation
    r"""Where tool-call arguments are checked against the original schema. Only `runtime` (in OpenRouter) is available in this release."""
