"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openrouter.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Literal, Optional
from typing_extensions import NotRequired, TypedDict


DeferredCustomSearchType = Literal["custom",]


class DeferredCustomSearchTypedDict(TypedDict):
    r"""Caller-executed search returning existing tool identities under result_key."""

    result_key: str
    tool_id: str
    type: DeferredCustomSearchType
    max_results: NotRequired[int]


class DeferredCustomSearch(BaseModel):
    r"""Caller-executed search returning existing tool identities under result_key."""

    result_key: str

    tool_id: str

    type: DeferredCustomSearchType

    max_results: Optional[int] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["max_results"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
