"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .deferredbm25search import DeferredBm25Search, DeferredBm25SearchTypedDict
from .deferredcustomsearch import DeferredCustomSearch, DeferredCustomSearchTypedDict
from .deferredregexsearch import DeferredRegexSearch, DeferredRegexSearchTypedDict
from openrouter.utils import get_discriminator
from pydantic import Discriminator, Tag
from typing import Union
from typing_extensions import Annotated, TypeAliasType


DeferredToolsSearchStrategyTypedDict = TypeAliasType(
    "DeferredToolsSearchStrategyTypedDict",
    Union[
        DeferredRegexSearchTypedDict,
        DeferredBm25SearchTypedDict,
        DeferredCustomSearchTypedDict,
    ],
)
r"""Router-local regex/BM25 or caller-owned custom search."""


DeferredToolsSearchStrategy = Annotated[
    Union[
        Annotated[DeferredBm25Search, Tag("bm25")],
        Annotated[DeferredCustomSearch, Tag("custom")],
        Annotated[DeferredRegexSearch, Tag("regex")],
    ],
    Discriminator(lambda m: get_discriminator(m, "type", "type")),
]
r"""Router-local regex/BM25 or caller-owned custom search."""
