"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openrouter.types import BaseModel
from typing_extensions import TypedDict


class DeletePrivateEndpointResponseDataTypedDict(TypedDict):
    id: str
    r"""Stable identifier of the private endpoint."""


class DeletePrivateEndpointResponseData(BaseModel):
    id: str
    r"""Stable identifier of the private endpoint."""


class DeletePrivateEndpointResponseTypedDict(TypedDict):
    data: DeletePrivateEndpointResponseDataTypedDict


class DeletePrivateEndpointResponse(BaseModel):
    data: DeletePrivateEndpointResponseData
