"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openrouter.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class DeleteInternRequestTypedDict(TypedDict):
    r"""Optional consent for a teardown that discards the workspace."""

    acknowledge_workspace_loss: NotRequired[bool]
    r"""Delete even though the workspace backup was not confirmed. Defaults to false, which refuses the teardown when a workspace archive is missing."""


class DeleteInternRequest(BaseModel):
    r"""Optional consent for a teardown that discards the workspace."""

    acknowledge_workspace_loss: Optional[bool] = False
    r"""Delete even though the workspace backup was not confirmed. Defaults to false, which refuses the teardown when a workspace archive is missing."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["acknowledge_workspace_loss"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
