"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .toolcallstatus import ToolCallStatus
from openrouter.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
import pydantic
from pydantic import ConfigDict, model_serializer
from typing import Any, Dict, List, Literal
from typing_extensions import Annotated, NotRequired, TypedDict


class FunctionCallItemSubagentItemTypedDict(TypedDict):
    type: str


class FunctionCallItemSubagentItem(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True, arbitrary_types_allowed=True, extra="allow"
    )
    __pydantic_extra__: Dict[str, Any] = pydantic.Field(init=False)

    type: str

    @property
    def additional_properties(self):
        return self.__pydantic_extra__

    @additional_properties.setter
    def additional_properties(self, value):
        self.__pydantic_extra__ = value  # pyright: ignore[reportIncompatibleVariableOverride]


FunctionCallItemType = Literal["function_call",]


class FunctionCallItemTypedDict(TypedDict):
    r"""A function call initiated by the model"""

    arguments: str
    call_id: str
    name: str
    type: FunctionCallItemType
    async_: NotRequired[Nullable[bool]]
    r"""True when the model called a tool declared with `async: true` and may continue its turn before the output is returned. Return the result in a later request as a `function_call_output` with this `call_id`."""
    id: NotRequired[Nullable[str]]
    namespace: NotRequired[Nullable[str]]
    r"""Namespace qualifier for tools registered as part of a namespace tool group (e.g. an MCP server)"""
    status: NotRequired[Nullable[ToolCallStatus]]
    subagent_id: NotRequired[Nullable[str]]
    r"""EXPERIMENTAL — subject to change without notice. String id that matches the `call_id` of the `openrouter:subagent` server tool call that spawned the subagent. Present on every `function_call` item the subagent projects; absent on ordinary function calls."""
    subagent_items: NotRequired[Nullable[List[FunctionCallItemSubagentItemTypedDict]]]
    r"""EXPERIMENTAL — subject to change without notice. The subagent's output items produced on this turn. Treat this as an opaque object; you must replay it in the request so that the subagent can continue execution of the tool with the same context. If a subagent created multiple parallel tool calls, only the first tool call will have this field. The other tool calls will only have `subagent_id`. Present only if the tool call originates from a subagent spawned by the `openrouter:subagent` server tool."""


class FunctionCallItem(BaseModel):
    r"""A function call initiated by the model"""

    arguments: str

    call_id: str

    name: str

    type: FunctionCallItemType

    async_: Annotated[OptionalNullable[bool], pydantic.Field(alias="async")] = UNSET
    r"""True when the model called a tool declared with `async: true` and may continue its turn before the output is returned. Return the result in a later request as a `function_call_output` with this `call_id`."""

    id: OptionalNullable[str] = UNSET

    namespace: OptionalNullable[str] = UNSET
    r"""Namespace qualifier for tools registered as part of a namespace tool group (e.g. an MCP server)"""

    status: OptionalNullable[ToolCallStatus] = UNSET

    subagent_id: OptionalNullable[str] = UNSET
    r"""EXPERIMENTAL — subject to change without notice. String id that matches the `call_id` of the `openrouter:subagent` server tool call that spawned the subagent. Present on every `function_call` item the subagent projects; absent on ordinary function calls."""

    subagent_items: OptionalNullable[List[FunctionCallItemSubagentItem]] = UNSET
    r"""EXPERIMENTAL — subject to change without notice. The subagent's output items produced on this turn. Treat this as an opaque object; you must replay it in the request so that the subagent can continue execution of the tool with the same context. If a subagent created multiple parallel tool calls, only the first tool call will have this field. The other tool calls will only have `subagent_id`. Present only if the tool call originates from a subagent spawned by the `openrouter:subagent` server tool."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["async", "id", "namespace", "status", "subagent_id", "subagent_items"]
        )
        nullable_fields = set(
            ["async", "id", "namespace", "status", "subagent_id", "subagent_items"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    FunctionCallItem.model_rebuild()
except NameError:
    pass
