"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .imagegenerationusage import ImageGenerationUsage, ImageGenerationUsageTypedDict
from openrouter.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class ImageGenerationResponseDataTypedDict(TypedDict):
    b64_json: str
    r"""Base64-encoded image bytes"""
    media_type: NotRequired[str]
    r"""Media type (MIME type) of the image. Omitted when the output is a standard raster format (PNG). Present for non-raster outputs such as SVG (`image/svg+xml`)."""


class ImageGenerationResponseData(BaseModel):
    b64_json: str
    r"""Base64-encoded image bytes"""

    media_type: Optional[str] = None
    r"""Media type (MIME type) of the image. Omitted when the output is a standard raster format (PNG). Present for non-raster outputs such as SVG (`image/svg+xml`)."""


class ImageGenerationResponseTypedDict(TypedDict):
    r"""Image generation response"""

    created: int
    r"""Unix timestamp (seconds) when the image was generated"""
    data: List[ImageGenerationResponseDataTypedDict]
    r"""Generated images"""
    usage: NotRequired[ImageGenerationUsageTypedDict]
    r"""Token and cost usage for the image generation request, when available"""


class ImageGenerationResponse(BaseModel):
    r"""Image generation response"""

    created: int
    r"""Unix timestamp (seconds) when the image was generated"""

    data: List[ImageGenerationResponseData]
    r"""Generated images"""

    usage: Optional[ImageGenerationUsage] = None
    r"""Token and cost usage for the image generation request, when available"""
