"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .imagegenerationusage import ImageGenerationUsage, ImageGenerationUsageTypedDict
from openrouter.types import BaseModel
from typing import Literal, Optional
from typing_extensions import NotRequired, TypedDict


ImageGenCompletedEventType = Literal["image_generation.completed",]
r"""The event type"""


class ImageGenCompletedEventTypedDict(TypedDict):
    r"""Emitted when generation completes and the final image is available"""

    b64_json: str
    r"""Base64-encoded final image data"""
    created: int
    r"""Unix timestamp (seconds) when the image was generated"""
    type: ImageGenCompletedEventType
    r"""The event type"""
    media_type: NotRequired[str]
    r"""Media type (MIME type) of the image. Omitted when the output is a standard raster format (PNG). Present for non-raster outputs such as SVG (`image/svg+xml`)."""
    usage: NotRequired[ImageGenerationUsageTypedDict]
    r"""Token and cost usage for the image generation request, when available"""


class ImageGenCompletedEvent(BaseModel):
    r"""Emitted when generation completes and the final image is available"""

    b64_json: str
    r"""Base64-encoded final image data"""

    created: int
    r"""Unix timestamp (seconds) when the image was generated"""

    type: ImageGenCompletedEventType
    r"""The event type"""

    media_type: Optional[str] = None
    r"""Media type (MIME type) of the image. Omitted when the output is a standard raster format (PNG). Present for non-raster outputs such as SVG (`image/svg+xml`)."""

    usage: Optional[ImageGenerationUsage] = None
    r"""Token and cost usage for the image generation request, when available"""
