"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openrouter.types import BaseModel, UnrecognizedStr
from openrouter.utils import validate_open_enum
from pydantic.functional_validators import PlainValidator
from typing import Literal, Optional, Union
from typing_extensions import Annotated, NotRequired, TypedDict


Billable = Union[
    Literal[
        "output_image",
        "input_image",
        "input_font",
        "input_reference",
        "input_text",
    ],
    UnrecognizedStr,
]


Unit = Union[
    Literal[
        "image",
        "megapixel",
        "token",
    ],
    UnrecognizedStr,
]


class ImagePricingEntryTypedDict(TypedDict):
    r"""One billable pricing line for an image provider."""

    billable: Billable
    cost_usd: float
    unit: Unit
    variant: NotRequired[str]


class ImagePricingEntry(BaseModel):
    r"""One billable pricing line for an image provider."""

    billable: Annotated[Billable, PlainValidator(validate_open_enum(False))]

    cost_usd: float

    unit: Annotated[Unit, PlainValidator(validate_open_enum(False))]

    variant: Optional[str] = None
