"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openrouter.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import Literal
from typing_extensions import NotRequired, TypedDict


class ImageGenStreamErrorEventErrorTypedDict(TypedDict):
    r"""Provider error details"""

    message: str
    r"""Provider error message"""
    code: NotRequired[Nullable[str]]
    r"""Provider error code, when supplied"""
    param: NotRequired[Nullable[str]]
    r"""Request parameter associated with the error, when supplied"""
    type: NotRequired[Nullable[str]]
    r"""Provider error type, when supplied"""


class ImageGenStreamErrorEventError(BaseModel):
    r"""Provider error details"""

    message: str
    r"""Provider error message"""

    code: OptionalNullable[str] = UNSET
    r"""Provider error code, when supplied"""

    param: OptionalNullable[str] = UNSET
    r"""Request parameter associated with the error, when supplied"""

    type: OptionalNullable[str] = UNSET
    r"""Provider error type, when supplied"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["code", "param", "type"]
        nullable_fields = ["code", "param", "type"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m


ImageGenStreamErrorEventType = Literal["error",]
r"""The event type"""


class ImageGenStreamErrorEventTypedDict(TypedDict):
    r"""Emitted when streaming generation fails after the SSE response starts"""

    error: ImageGenStreamErrorEventErrorTypedDict
    r"""Provider error details"""
    type: ImageGenStreamErrorEventType
    r"""The event type"""


class ImageGenStreamErrorEvent(BaseModel):
    r"""Emitted when streaming generation fails after the SSE response starts"""

    error: ImageGenStreamErrorEventError
    r"""Provider error details"""

    type: ImageGenStreamErrorEventType
    r"""The event type"""
