"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .imageoutputmodality import ImageOutputModality
from .inputmodality import InputModality
from openrouter.types import BaseModel
from openrouter.utils import validate_open_enum
from pydantic.functional_validators import PlainValidator
from typing import List
from typing_extensions import Annotated, TypedDict


class ImageModelArchitectureTypedDict(TypedDict):
    input_modalities: List[InputModality]
    r"""Supported input modalities"""
    output_modalities: List[ImageOutputModality]
    r"""Supported output modalities"""


class ImageModelArchitecture(BaseModel):
    input_modalities: List[
        Annotated[InputModality, PlainValidator(validate_open_enum(False))]
    ]
    r"""Supported input modalities"""

    output_modalities: List[
        Annotated[ImageOutputModality, PlainValidator(validate_open_enum(False))]
    ]
    r"""Supported output modalities"""
