"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .internchatmessagecontent import (
    InternChatMessageContent,
    InternChatMessageContentTypedDict,
)
from openrouter.types import BaseModel, Nullable, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Literal
from typing_extensions import TypedDict


InternChatDeveloperMessageRole = Literal["developer",]


class InternChatDeveloperMessageTypedDict(TypedDict):
    r"""A developer message. Accepted for client compatibility and not forwarded."""

    content: Nullable[InternChatMessageContentTypedDict]
    r"""Message text as a string or a list of text parts. Assistant history may carry null. Only the last message is read; earlier messages are accepted so ordinary clients can resend history."""
    role: InternChatDeveloperMessageRole


class InternChatDeveloperMessage(BaseModel):
    r"""A developer message. Accepted for client compatibility and not forwarded."""

    content: Nullable[InternChatMessageContent]
    r"""Message text as a string or a list of text parts. Assistant history may carry null. Only the last message is read; earlier messages are accepted so ordinary clients can resend history."""

    role: InternChatDeveloperMessageRole

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m
