"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openrouter.types import BaseModel
from typing_extensions import TypedDict


class InternChatEchoedToolCallFunctionTypedDict(TypedDict):
    r"""The function name and JSON arguments string exactly as streamed."""

    arguments: str
    name: str


class InternChatEchoedToolCallFunction(BaseModel):
    r"""The function name and JSON arguments string exactly as streamed."""

    arguments: str

    name: str
