"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openrouter.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class InternInvokeRequestTypedDict(TypedDict):
    r"""A prompt to run on the intern without holding a connection open."""

    input: str
    r"""The prompt for the run, at most 32000 characters."""
    session_id: NotRequired[str]
    r"""The session to run in. Send the `session_id` from an earlier `202` to continue that conversation, for example to hand the intern a decision on a case it is working. Omit it to start a new session. Only a `session_id` this endpoint issued to the same caller on the same intern is accepted; any other is refused with `404`."""


class InternInvokeRequest(BaseModel):
    r"""A prompt to run on the intern without holding a connection open."""

    input: str
    r"""The prompt for the run, at most 32000 characters."""

    session_id: Optional[str] = None
    r"""The session to run in. Send the `session_id` from an earlier `202` to continue that conversation, for example to hand the intern a decision on a case it is working. Omit it to start a new session. Only a `session_id` this endpoint issued to the same caller on the same intern is accepted; any other is refused with `404`."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["session_id"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
