"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .internchattextpart import InternChatTextPart, InternChatTextPartTypedDict
from typing import List, Union
from typing_extensions import TypeAliasType


InternChatMessageContentTypedDict = TypeAliasType(
    "InternChatMessageContentTypedDict", Union[str, List[InternChatTextPartTypedDict]]
)
r"""Message text as a string or a list of text parts. Assistant history may carry null. Only the last message is read; earlier messages are accepted so ordinary clients can resend history."""


InternChatMessageContent = TypeAliasType(
    "InternChatMessageContent", Union[str, List[InternChatTextPart]]
)
r"""Message text as a string or a list of text parts. Assistant history may carry null. Only the last message is read; earlier messages are accepted so ordinary clients can resend history."""
