"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openrouter.types import BaseModel
from typing import Literal
from typing_extensions import TypedDict


InternChatTextPartType = Literal["text",]


class InternChatTextPartTypedDict(TypedDict):
    r"""One text part of a message."""

    text: str
    type: InternChatTextPartType


class InternChatTextPart(BaseModel):
    r"""One text part of a message."""

    text: str

    type: InternChatTextPartType
