"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .internchattoolcallfunction import (
    InternChatToolCallFunction,
    InternChatToolCallFunctionTypedDict,
)
from openrouter.types import BaseModel
from typing import Literal
from typing_extensions import TypedDict


InternChatToolCallType = Literal["function",]


class InternChatToolCallTypedDict(TypedDict):
    r"""An `openrouter.provide_input` request. The run pauses on the daemon until a `tool` message answers it, the caller cancels it, or its interaction deadline passes."""

    function: InternChatToolCallFunctionTypedDict
    r"""The single tool this endpoint calls, asking the caller for input."""
    id: str
    r"""The interaction id. Send it back as `tool_call_id` on the `tool` message that answers it."""
    index: int
    type: InternChatToolCallType


class InternChatToolCall(BaseModel):
    r"""An `openrouter.provide_input` request. The run pauses on the daemon until a `tool` message answers it, the caller cancels it, or its interaction deadline passes."""

    function: InternChatToolCallFunction
    r"""The single tool this endpoint calls, asking the caller for input."""

    id: str
    r"""The interaction id. Send it back as `tool_call_id` on the `tool` message that answers it."""

    index: int

    type: InternChatToolCallType
