"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .internchatassistantmessage import (
    InternChatAssistantMessage,
    InternChatAssistantMessageTypedDict,
)
from .internchatdevelopermessage import (
    InternChatDeveloperMessage,
    InternChatDeveloperMessageTypedDict,
)
from .internchatsystemmessage import (
    InternChatSystemMessage,
    InternChatSystemMessageTypedDict,
)
from .internchattoolmessage import InternChatToolMessage, InternChatToolMessageTypedDict
from .internchatusermessage import InternChatUserMessage, InternChatUserMessageTypedDict
from openrouter.utils import get_discriminator
from pydantic import Discriminator, Tag
from typing import Union
from typing_extensions import Annotated, TypeAliasType


InternChatMessageTypedDict = TypeAliasType(
    "InternChatMessageTypedDict",
    Union[
        InternChatSystemMessageTypedDict,
        InternChatDeveloperMessageTypedDict,
        InternChatUserMessageTypedDict,
        InternChatAssistantMessageTypedDict,
        InternChatToolMessageTypedDict,
    ],
)
r"""One OpenAI-compatible chat message, discriminated by `role`."""


InternChatMessage = Annotated[
    Union[
        Annotated[InternChatAssistantMessage, Tag("assistant")],
        Annotated[InternChatDeveloperMessage, Tag("developer")],
        Annotated[InternChatSystemMessage, Tag("system")],
        Annotated[InternChatToolMessage, Tag("tool")],
        Annotated[InternChatUserMessage, Tag("user")],
    ],
    Discriminator(lambda m: get_discriminator(m, "role", "role")),
]
r"""One OpenAI-compatible chat message, discriminated by `role`."""
