"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openrouter.types import BaseModel
from typing import Literal
from typing_extensions import TypedDict


InternChatToolCallFunctionName = Literal["openrouter.provide_input",]


class InternChatToolCallFunctionTypedDict(TypedDict):
    r"""The single tool this endpoint calls, asking the caller for input."""

    arguments: str
    r"""A JSON object string describing the interaction. A permission request is `{\"kind\":\"permission\",\"operation\":<tool name or null>,\"options\":[<permission option kinds>]}`. A question is `{\"kind\":\"elicitation\",\"message\":<question>,\"fields\":[<field descriptors>]}`."""
    name: InternChatToolCallFunctionName


class InternChatToolCallFunction(BaseModel):
    r"""The single tool this endpoint calls, asking the caller for input."""

    arguments: str
    r"""A JSON object string describing the interaction. A permission request is `{\"kind\":\"permission\",\"operation\":<tool name or null>,\"options\":[<permission option kinds>]}`. A question is `{\"kind\":\"elicitation\",\"message\":<question>,\"fields\":[<field descriptors>]}`."""

    name: InternChatToolCallFunctionName
