"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openrouter.types import BaseModel, UnrecognizedStr
from typing import Literal, Union
from typing_extensions import TypedDict


InternChatErrorMetadataReason = Union[
    Literal[
        "attachment_failed",
        "bad_request",
        "busy",
        "client_closed_request",
        "interaction_not_pending",
        "interaction_unknown",
        "intern_not_ready",
        "intern_rejected",
        "intern_unreachable",
        "not_found",
        "payload_too_large",
        "rate_limited",
        "run_ended",
        "stream_severed",
        "timeout",
        "turn_failed",
    ],
    UnrecognizedStr,
]
r"""A stable reason a client can branch on."""


class InternChatErrorMetadataTypedDict(TypedDict):
    r"""Machine-readable detail for the failure."""

    reason: InternChatErrorMetadataReason
    r"""A stable reason a client can branch on."""
    retryable: bool
    r"""Whether the same request may be sent again unchanged. Always `true` for the transient refusals — `busy`, `intern_not_ready`, `intern_unreachable`, `rate_limited`, `stream_severed` and `timeout` — and always `false` for the ones a retry cannot fix. For `turn_failed` it varies by failure and is the intern's own classification of what went wrong: `true` for an upstream overload, rate limit, timeout or transport fault, `false` for an authentication or bad-request failure that would be rejected the same way again. Branch on this field rather than on `reason` when deciding whether to retry. A `429`, and a `409` or `503` with reason `busy`, also carry a `Retry-After` header saying how long to wait."""


class InternChatErrorMetadata(BaseModel):
    r"""Machine-readable detail for the failure."""

    reason: InternChatErrorMetadataReason
    r"""A stable reason a client can branch on."""

    retryable: bool
    r"""Whether the same request may be sent again unchanged. Always `true` for the transient refusals — `busy`, `intern_not_ready`, `intern_unreachable`, `rate_limited`, `stream_severed` and `timeout` — and always `false` for the ones a retry cannot fix. For `turn_failed` it varies by failure and is the intern's own classification of what went wrong: `true` for an upstream overload, rate limit, timeout or transport fault, `false` for an authentication or bad-request failure that would be rejected the same way again. Branch on this field rather than on `reason` when deciding whether to retry. A `429`, and a `409` or `503` with reason `busy`, also carry a `Retry-After` header saying how long to wait."""
