"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .internchaterrormetadata import (
    InternChatErrorMetadata,
    InternChatErrorMetadataTypedDict,
)
from openrouter.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class InternChatErrorTypedDict(TypedDict):
    r"""The OpenAI-compatible error object. `metadata` is present on refusals from the chat route. Authentication refusals (`401`), the departed-creator `403` and the programme `404` carry only `code` and `message`."""

    code: int
    r"""The HTTP status of the response."""
    message: str
    metadata: NotRequired[InternChatErrorMetadataTypedDict]
    r"""Machine-readable detail for the failure."""


class InternChatError(BaseModel):
    r"""The OpenAI-compatible error object. `metadata` is present on refusals from the chat route. Authentication refusals (`401`), the departed-creator `403` and the programme `404` carry only `code` and `message`."""

    code: int
    r"""The HTTP status of the response."""

    message: str

    metadata: Optional[InternChatErrorMetadata] = None
    r"""Machine-readable detail for the failure."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["metadata"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
