"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .enduser import EndUser, EndUserTypedDict
from openrouter.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class ListEndUsersResponseTypedDict(TypedDict):
    data: List[EndUserTypedDict]
    total_count: int
    r"""Number of registrations matching the filters before pagination."""


class ListEndUsersResponse(BaseModel):
    data: List[EndUser]

    total_count: int
    r"""Number of registrations matching the filters before pagination."""
