"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .inputmodality import InputModality
from .instructtype import InstructType
from .outputmodality import OutputModality
from .publicendpoint import PublicEndpoint, PublicEndpointTypedDict
from openrouter.types import BaseModel, Nullable, UNSET_SENTINEL, UnrecognizedStr
from pydantic import model_serializer
from typing import List, Literal, Union
from typing_extensions import TypedDict


Tokenizer = Union[
    Literal[
        "Router",
        "Media",
        "Other",
        "GPT",
        "Claude",
        "Gemini",
        "Gemma",
        "Grok",
        "Cohere",
        "Nova",
        "Qwen",
        "Yi",
        "DeepSeek",
        "Mistral",
        "Llama2",
        "Llama3",
        "Llama4",
        "PaLM",
        "RWKV",
        "Qwen3",
    ],
    UnrecognizedStr,
]
r"""Tokenizer type used by the model"""


class ArchitectureTypedDict(TypedDict):
    r"""Model architecture information"""

    input_modalities: List[InputModality]
    r"""Supported input modalities"""
    instruct_type: Nullable[InstructType]
    r"""Instruction format type"""
    modality: Nullable[str]
    r"""Primary modality of the model"""
    output_modalities: List[OutputModality]
    r"""Supported output modalities"""
    tokenizer: Nullable[Tokenizer]


class Architecture(BaseModel):
    r"""Model architecture information"""

    input_modalities: List[InputModality]
    r"""Supported input modalities"""

    instruct_type: Nullable[InstructType]
    r"""Instruction format type"""

    modality: Nullable[str]
    r"""Primary modality of the model"""

    output_modalities: List[OutputModality]
    r"""Supported output modalities"""

    tokenizer: Nullable[Tokenizer]

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


class ListEndpointsResponseTypedDict(TypedDict):
    r"""List of available endpoints for a model"""

    architecture: ArchitectureTypedDict
    created: int
    r"""Unix timestamp of when the model was created"""
    description: str
    r"""Description of the model"""
    endpoints: List[PublicEndpointTypedDict]
    r"""List of available endpoints for this model"""
    id: str
    r"""Unique identifier for the model"""
    name: str
    r"""Display name of the model"""


class ListEndpointsResponse(BaseModel):
    r"""List of available endpoints for a model"""

    architecture: Architecture

    created: int
    r"""Unix timestamp of when the model was created"""

    description: str
    r"""Description of the model"""

    endpoints: List[PublicEndpoint]
    r"""List of available endpoints for this model"""

    id: str
    r"""Unique identifier for the model"""

    name: str
    r"""Display name of the model"""
