"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openrouter.types import BaseModel
from typing import Literal
from typing_extensions import TypedDict


MessagesToolAdditionBlockTypeToolReference = Literal["tool_reference",]


class MessagesToolAdditionBlockToolTypedDict(TypedDict):
    name: str
    type: MessagesToolAdditionBlockTypeToolReference


class MessagesToolAdditionBlockTool(BaseModel):
    name: str

    type: MessagesToolAdditionBlockTypeToolReference


TypeToolAddition = Literal["tool_addition",]


class MessagesToolAdditionBlockTypedDict(TypedDict):
    r"""Loads a previously deferred tool (declared in `tools` with `defer_loading: true`) mid-conversation without invalidating the prompt cache. Only valid in `role: \"system\"` messages. Not supported on Claude Sonnet 5 or models older than Claude Opus 4.8."""

    tool: MessagesToolAdditionBlockToolTypedDict
    type: TypeToolAddition


class MessagesToolAdditionBlock(BaseModel):
    r"""Loads a previously deferred tool (declared in `tools` with `defer_loading: true`) mid-conversation without invalidating the prompt cache. Only valid in `role: \"system\"` messages. Not supported on Claude Sonnet 5 or models older than Claude Opus 4.8."""

    tool: MessagesToolAdditionBlockTool

    type: TypeToolAddition
