"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openrouter.types import BaseModel
from typing import Literal
from typing_extensions import TypedDict


OpenResponsesWebSearchCallInProgressType = Literal[
    "response.web_search_call.in_progress",
]


class OpenResponsesWebSearchCallInProgressTypedDict(TypedDict):
    r"""Web search call in progress"""

    type: OpenResponsesWebSearchCallInProgressType
    item_id: str
    output_index: float
    sequence_number: float


class OpenResponsesWebSearchCallInProgress(BaseModel):
    r"""Web search call in progress"""

    type: OpenResponsesWebSearchCallInProgressType

    item_id: str

    output_index: float

    sequence_number: float
