"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .apierrortype import APIErrorType
from .applypatchservertool import ApplyPatchServerTool, ApplyPatchServerToolTypedDict
from .baseinputs_union import BaseInputsUnion, BaseInputsUnionTypedDict
from .basereasoningconfig import BaseReasoningConfig, BaseReasoningConfigTypedDict
from .codeinterpreterservertool import (
    CodeInterpreterServerTool,
    CodeInterpreterServerToolTypedDict,
)
from .codexlocalshelltool import CodexLocalShellTool, CodexLocalShellToolTypedDict
from .computeruseservertool import ComputerUseServerTool, ComputerUseServerToolTypedDict
from .customtool import CustomTool, CustomToolTypedDict
from .filesearchservertool import FileSearchServerTool, FileSearchServerToolTypedDict
from .imagegenerationservertool import (
    ImageGenerationServerTool,
    ImageGenerationServerToolTypedDict,
)
from .incompletedetails import IncompleteDetails, IncompleteDetailsTypedDict
from .legacy_websearchservertool import (
    LegacyWebSearchServerTool,
    LegacyWebSearchServerToolTypedDict,
)
from .mcpservertool import McpServerTool, McpServerToolTypedDict
from .openairesponsesresponsestatus import OpenAIResponsesResponseStatus
from .openairesponsestoolchoice_union import (
    OpenAIResponsesToolChoiceUnion,
    OpenAIResponsesToolChoiceUnionTypedDict,
)
from .openroutermetadata import OpenRouterMetadata, OpenRouterMetadataTypedDict
from .outputitems import OutputItems, OutputItemsTypedDict
from .preview_20250311_websearchservertool import (
    Preview20250311WebSearchServerTool,
    Preview20250311WebSearchServerToolTypedDict,
)
from .preview_websearchservertool import (
    PreviewWebSearchServerTool,
    PreviewWebSearchServerToolTypedDict,
)
from .responseserrorfield import ResponsesErrorField, ResponsesErrorFieldTypedDict
from .shellservertool import ShellServerTool, ShellServerToolTypedDict
from .storedprompttemplate import StoredPromptTemplate, StoredPromptTemplateTypedDict
from .textextendedconfig import TextExtendedConfig, TextExtendedConfigTypedDict
from .truncation import Truncation
from .usage import Usage, UsageTypedDict
from .websearchservertool import WebSearchServerTool, WebSearchServerToolTypedDict
from functools import partial
from openrouter.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from openrouter.utils.unions import parse_open_union
from pydantic import ConfigDict, model_serializer
from pydantic.functional_validators import BeforeValidator
from typing import Any, Dict, List, Literal, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


OpenResponsesResultObject = Literal["response",]


OpenResponsesResultType = Literal["function",]


class OpenResponsesResultToolFunctionTypedDict(TypedDict):
    r"""Function tool definition"""

    name: str
    parameters: Nullable[Dict[str, Nullable[Any]]]
    type: OpenResponsesResultType
    description: NotRequired[Nullable[str]]
    strict: NotRequired[Nullable[bool]]


class OpenResponsesResultToolFunction(BaseModel):
    r"""Function tool definition"""

    name: str

    parameters: Nullable[Dict[str, Nullable[Any]]]

    type: OpenResponsesResultType

    description: OptionalNullable[str] = UNSET

    strict: OptionalNullable[bool] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["description", "strict"])
        nullable_fields = set(["description", "parameters", "strict"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


OpenResponsesResultToolUnionTypedDict = TypeAliasType(
    "OpenResponsesResultToolUnionTypedDict",
    Union[
        CodexLocalShellToolTypedDict,
        ApplyPatchServerToolTypedDict,
        ShellServerToolTypedDict,
        CodeInterpreterServerToolTypedDict,
        CustomToolTypedDict,
        ComputerUseServerToolTypedDict,
        OpenResponsesResultToolFunctionTypedDict,
        FileSearchServerToolTypedDict,
        LegacyWebSearchServerToolTypedDict,
        WebSearchServerToolTypedDict,
        Preview20250311WebSearchServerToolTypedDict,
        PreviewWebSearchServerToolTypedDict,
        McpServerToolTypedDict,
        ImageGenerationServerToolTypedDict,
    ],
)


class UnknownOpenResponsesResultToolUnion(BaseModel):
    r"""A OpenResponsesResultToolUnion variant the SDK doesn't recognize. Preserves the raw payload."""

    type: Literal["UNKNOWN"] = "UNKNOWN"
    raw: Any
    is_unknown: Literal[True] = True

    model_config = ConfigDict(frozen=True)


_OPEN_RESPONSES_RESULT_TOOL_UNION_VARIANTS: dict[str, Any] = {
    "function": OpenResponsesResultToolFunction,
    "web_search_preview": PreviewWebSearchServerTool,
    "web_search_preview_2025_03_11": Preview20250311WebSearchServerTool,
    "web_search": LegacyWebSearchServerTool,
    "web_search_2025_08_26": WebSearchServerTool,
    "file_search": FileSearchServerTool,
    "computer_use_preview": ComputerUseServerTool,
    "code_interpreter": CodeInterpreterServerTool,
    "mcp": McpServerTool,
    "image_generation": ImageGenerationServerTool,
    "local_shell": CodexLocalShellTool,
    "shell": ShellServerTool,
    "apply_patch": ApplyPatchServerTool,
    "custom": CustomTool,
}


OpenResponsesResultToolUnion = Annotated[
    Union[
        OpenResponsesResultToolFunction,
        PreviewWebSearchServerTool,
        Preview20250311WebSearchServerTool,
        LegacyWebSearchServerTool,
        WebSearchServerTool,
        FileSearchServerTool,
        ComputerUseServerTool,
        CodeInterpreterServerTool,
        McpServerTool,
        ImageGenerationServerTool,
        CodexLocalShellTool,
        ShellServerTool,
        ApplyPatchServerTool,
        CustomTool,
        UnknownOpenResponsesResultToolUnion,
    ],
    BeforeValidator(
        partial(
            parse_open_union,
            disc_key="type",
            variants=_OPEN_RESPONSES_RESULT_TOOL_UNION_VARIANTS,
            unknown_cls=UnknownOpenResponsesResultToolUnion,
            union_name="OpenResponsesResultToolUnion",
        )
    ),
]


class OpenResponsesResultTypedDict(TypedDict):
    r"""Complete non-streaming response from the Responses API"""

    completed_at: Nullable[int]
    created_at: int
    error: Nullable[ResponsesErrorFieldTypedDict]
    r"""Error information returned from the API"""
    frequency_penalty: Nullable[float]
    id: str
    incomplete_details: Nullable[IncompleteDetailsTypedDict]
    instructions: Nullable[BaseInputsUnionTypedDict]
    metadata: Nullable[Dict[str, str]]
    r"""Metadata key-value pairs for the request. Keys must be ≤64 characters and cannot contain brackets. Values must be ≤512 characters. Maximum 16 pairs allowed."""
    model: str
    object: OpenResponsesResultObject
    output: List[OutputItemsTypedDict]
    parallel_tool_calls: bool
    presence_penalty: Nullable[float]
    status: OpenAIResponsesResponseStatus
    temperature: Nullable[float]
    tool_choice: OpenAIResponsesToolChoiceUnionTypedDict
    tools: List[OpenResponsesResultToolUnionTypedDict]
    top_p: Nullable[float]
    background: NotRequired[Nullable[bool]]
    max_output_tokens: NotRequired[Nullable[int]]
    max_tool_calls: NotRequired[Nullable[int]]
    output_text: NotRequired[str]
    previous_response_id: NotRequired[Nullable[str]]
    prompt: NotRequired[Nullable[StoredPromptTemplateTypedDict]]
    prompt_cache_key: NotRequired[Nullable[str]]
    reasoning: NotRequired[Nullable[BaseReasoningConfigTypedDict]]
    safety_identifier: NotRequired[Nullable[str]]
    service_tier: NotRequired[Nullable[str]]
    store: NotRequired[bool]
    text: NotRequired[TextExtendedConfigTypedDict]
    r"""Text output configuration including format and verbosity"""
    top_logprobs: NotRequired[int]
    truncation: NotRequired[Nullable[Truncation]]
    usage: NotRequired[Nullable[UsageTypedDict]]
    r"""Token usage information for the response"""
    user: NotRequired[Nullable[str]]
    error_type: NotRequired[APIErrorType]
    r"""Canonical OpenRouter error type, stable across all API formats"""
    openrouter_metadata: NotRequired[OpenRouterMetadataTypedDict]


class OpenResponsesResult(BaseModel):
    r"""Complete non-streaming response from the Responses API"""

    completed_at: Nullable[int]

    created_at: int

    error: Nullable[ResponsesErrorField]
    r"""Error information returned from the API"""

    frequency_penalty: Nullable[float]

    id: str

    incomplete_details: Nullable[IncompleteDetails]

    instructions: Nullable[BaseInputsUnion]

    metadata: Nullable[Dict[str, str]]
    r"""Metadata key-value pairs for the request. Keys must be ≤64 characters and cannot contain brackets. Values must be ≤512 characters. Maximum 16 pairs allowed."""

    model: str

    object: OpenResponsesResultObject

    output: List[OutputItems]

    parallel_tool_calls: bool

    presence_penalty: Nullable[float]

    status: OpenAIResponsesResponseStatus

    temperature: Nullable[float]

    tool_choice: OpenAIResponsesToolChoiceUnion

    tools: List[OpenResponsesResultToolUnion]

    top_p: Nullable[float]

    background: OptionalNullable[bool] = UNSET

    max_output_tokens: OptionalNullable[int] = UNSET

    max_tool_calls: OptionalNullable[int] = UNSET

    output_text: Optional[str] = None

    previous_response_id: OptionalNullable[str] = UNSET

    prompt: OptionalNullable[StoredPromptTemplate] = UNSET

    prompt_cache_key: OptionalNullable[str] = UNSET

    reasoning: OptionalNullable[BaseReasoningConfig] = UNSET

    safety_identifier: OptionalNullable[str] = UNSET

    service_tier: OptionalNullable[str] = UNSET

    store: Optional[bool] = None

    text: Optional[TextExtendedConfig] = None
    r"""Text output configuration including format and verbosity"""

    top_logprobs: Optional[int] = None

    truncation: OptionalNullable[Truncation] = UNSET

    usage: OptionalNullable[Usage] = UNSET
    r"""Token usage information for the response"""

    user: OptionalNullable[str] = UNSET

    error_type: Optional[APIErrorType] = None
    r"""Canonical OpenRouter error type, stable across all API formats"""

    openrouter_metadata: Optional[OpenRouterMetadata] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "background",
                "max_output_tokens",
                "max_tool_calls",
                "output_text",
                "previous_response_id",
                "prompt",
                "prompt_cache_key",
                "reasoning",
                "safety_identifier",
                "service_tier",
                "store",
                "text",
                "top_logprobs",
                "truncation",
                "usage",
                "user",
                "error_type",
                "openrouter_metadata",
            ]
        )
        nullable_fields = set(
            [
                "background",
                "completed_at",
                "error",
                "frequency_penalty",
                "incomplete_details",
                "instructions",
                "max_output_tokens",
                "max_tool_calls",
                "metadata",
                "presence_penalty",
                "previous_response_id",
                "prompt",
                "prompt_cache_key",
                "reasoning",
                "safety_identifier",
                "service_tier",
                "temperature",
                "top_p",
                "truncation",
                "usage",
                "user",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
