"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .anthropicadvisortoolresult import (
    AnthropicAdvisorToolResult,
    AnthropicAdvisorToolResultTypedDict,
)
from .anthropicbashcodeexecutiontoolresult import (
    AnthropicBashCodeExecutionToolResult,
    AnthropicBashCodeExecutionToolResultTypedDict,
)
from .anthropiccodeexecutiontoolresult import (
    AnthropicCodeExecutionToolResult,
    AnthropicCodeExecutionToolResultTypedDict,
)
from .anthropiccompactionblock import (
    AnthropicCompactionBlock,
    AnthropicCompactionBlockTypedDict,
)
from .anthropiccontainerupload import (
    AnthropicContainerUpload,
    AnthropicContainerUploadTypedDict,
)
from .anthropicredactedthinkingblock import (
    AnthropicRedactedThinkingBlock,
    AnthropicRedactedThinkingBlockTypedDict,
)
from .anthropictextblock import AnthropicTextBlock, AnthropicTextBlockTypedDict
from .anthropictexteditorcodeexecutiontoolresult import (
    AnthropicTextEditorCodeExecutionToolResult,
    AnthropicTextEditorCodeExecutionToolResultTypedDict,
)
from .anthropicthinkingblock import (
    AnthropicThinkingBlock,
    AnthropicThinkingBlockTypedDict,
)
from .anthropictoolsearchtoolresult import (
    AnthropicToolSearchToolResult,
    AnthropicToolSearchToolResultTypedDict,
)
from .anthropictooluseblock import AnthropicToolUseBlock, AnthropicToolUseBlockTypedDict
from .anthropicwebfetchtoolresult import (
    AnthropicWebFetchToolResult,
    AnthropicWebFetchToolResultTypedDict,
)
from .anthropicwebsearchtoolresult import (
    AnthropicWebSearchToolResult,
    AnthropicWebSearchToolResultTypedDict,
)
from .oranthropicbashtoolresult import (
    ORAnthropicBashToolResult,
    ORAnthropicBashToolResultTypedDict,
)
from .oranthropicservertooluseblock import (
    ORAnthropicServerToolUseBlock,
    ORAnthropicServerToolUseBlockTypedDict,
)
from .oranthropicshelltoolresult import (
    ORAnthropicShellToolResult,
    ORAnthropicShellToolResultTypedDict,
)
from functools import partial
from openrouter.types import BaseModel
from openrouter.utils.unions import parse_open_union
from pydantic import ConfigDict
from pydantic.functional_validators import BeforeValidator
from typing import Any, Literal, Union
from typing_extensions import Annotated, TypeAliasType


ORAnthropicContentBlockTypedDict = TypeAliasType(
    "ORAnthropicContentBlockTypedDict",
    Union[
        AnthropicRedactedThinkingBlockTypedDict,
        AnthropicContainerUploadTypedDict,
        AnthropicCompactionBlockTypedDict,
        AnthropicTextBlockTypedDict,
        AnthropicAdvisorToolResultTypedDict,
        AnthropicThinkingBlockTypedDict,
        AnthropicToolSearchToolResultTypedDict,
        AnthropicCodeExecutionToolResultTypedDict,
        AnthropicBashCodeExecutionToolResultTypedDict,
        AnthropicTextEditorCodeExecutionToolResultTypedDict,
        AnthropicWebFetchToolResultTypedDict,
        AnthropicWebSearchToolResultTypedDict,
        AnthropicToolUseBlockTypedDict,
        ORAnthropicServerToolUseBlockTypedDict,
        ORAnthropicShellToolResultTypedDict,
        ORAnthropicBashToolResultTypedDict,
    ],
)


class UnknownORAnthropicContentBlock(BaseModel):
    r"""A ORAnthropicContentBlock variant the SDK doesn't recognize. Preserves the raw payload."""

    type: Literal["UNKNOWN"] = "UNKNOWN"
    raw: Any
    is_unknown: Literal[True] = True

    model_config = ConfigDict(frozen=True)


_OR_ANTHROPIC_CONTENT_BLOCK_VARIANTS: dict[str, Any] = {
    "advisor_tool_result": AnthropicAdvisorToolResult,
    "bash_code_execution_tool_result": AnthropicBashCodeExecutionToolResult,
    "code_execution_tool_result": AnthropicCodeExecutionToolResult,
    "compaction": AnthropicCompactionBlock,
    "container_upload": AnthropicContainerUpload,
    "openrouter_bash_tool_result": ORAnthropicBashToolResult,
    "openrouter_shell_tool_result": ORAnthropicShellToolResult,
    "redacted_thinking": AnthropicRedactedThinkingBlock,
    "server_tool_use": ORAnthropicServerToolUseBlock,
    "text": AnthropicTextBlock,
    "text_editor_code_execution_tool_result": AnthropicTextEditorCodeExecutionToolResult,
    "thinking": AnthropicThinkingBlock,
    "tool_search_tool_result": AnthropicToolSearchToolResult,
    "tool_use": AnthropicToolUseBlock,
    "web_fetch_tool_result": AnthropicWebFetchToolResult,
    "web_search_tool_result": AnthropicWebSearchToolResult,
}


ORAnthropicContentBlock = Annotated[
    Union[
        AnthropicAdvisorToolResult,
        AnthropicBashCodeExecutionToolResult,
        AnthropicCodeExecutionToolResult,
        AnthropicCompactionBlock,
        AnthropicContainerUpload,
        ORAnthropicBashToolResult,
        ORAnthropicShellToolResult,
        AnthropicRedactedThinkingBlock,
        ORAnthropicServerToolUseBlock,
        AnthropicTextBlock,
        AnthropicTextEditorCodeExecutionToolResult,
        AnthropicThinkingBlock,
        AnthropicToolSearchToolResult,
        AnthropicToolUseBlock,
        AnthropicWebFetchToolResult,
        AnthropicWebSearchToolResult,
        UnknownORAnthropicContentBlock,
    ],
    BeforeValidator(
        partial(
            parse_open_union,
            disc_key="type",
            variants=_OR_ANTHROPIC_CONTENT_BLOCK_VARIANTS,
            unknown_cls=UnknownORAnthropicContentBlock,
            union_name="ORAnthropicContentBlock",
        )
    ),
]
