"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openrouter.types import UnrecognizedStr
from typing import Literal, Union


ORAnthropicStopReason = Union[
    Literal[
        "end_turn",
        "max_tokens",
        "model_context_window_exceeded",
        "stop_sequence",
        "tool_use",
        "pause_turn",
        "refusal",
        "compaction",
    ],
    UnrecognizedStr,
]
