"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openrouter.types import BaseModel
from typing import Any, Dict, Literal
from typing_extensions import TypedDict


ORAnthropicToolSearchResultType = Literal["openrouter_tool_search_result",]


class ORAnthropicToolSearchResultTypedDict(TypedDict):
    r"""Router-owned deferred discovery result containing original selected tool definitions."""

    content: Dict[str, Any]
    tool_use_id: str
    type: ORAnthropicToolSearchResultType


class ORAnthropicToolSearchResult(BaseModel):
    r"""Router-owned deferred discovery result containing original selected tool definitions."""

    content: Dict[str, Any]

    tool_use_id: str

    type: ORAnthropicToolSearchResultType
