"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .anthropiccodeexecution20250825caller import (
    AnthropicCodeExecution20250825Caller,
    AnthropicCodeExecution20250825CallerTypedDict,
)
from .anthropiccodeexecution20260120caller import (
    AnthropicCodeExecution20260120Caller,
    AnthropicCodeExecution20260120CallerTypedDict,
)
from .anthropicdirectcaller import AnthropicDirectCaller, AnthropicDirectCallerTypedDict
from functools import partial
from openrouter.types import BaseModel
from openrouter.utils.unions import parse_open_union
from pydantic import ConfigDict
from pydantic.functional_validators import BeforeValidator
from typing import Any, Literal, Union
from typing_extensions import Annotated, TypeAliasType


ORAnthropicNullableCallerTypedDict = TypeAliasType(
    "ORAnthropicNullableCallerTypedDict",
    Union[
        AnthropicDirectCallerTypedDict,
        AnthropicCodeExecution20250825CallerTypedDict,
        AnthropicCodeExecution20260120CallerTypedDict,
    ],
)


class UnknownORAnthropicNullableCaller(BaseModel):
    r"""A ORAnthropicNullableCaller variant the SDK doesn't recognize. Preserves the raw payload."""

    type: Literal["UNKNOWN"] = "UNKNOWN"
    raw: Any
    is_unknown: Literal[True] = True

    model_config = ConfigDict(frozen=True)


_OR_ANTHROPIC_NULLABLE_CALLER_VARIANTS: dict[str, Any] = {
    "code_execution_20250825": AnthropicCodeExecution20250825Caller,
    "code_execution_20260120": AnthropicCodeExecution20260120Caller,
    "direct": AnthropicDirectCaller,
}


ORAnthropicNullableCaller = Annotated[
    Union[
        AnthropicCodeExecution20250825Caller,
        AnthropicCodeExecution20260120Caller,
        AnthropicDirectCaller,
        UnknownORAnthropicNullableCaller,
    ],
    BeforeValidator(
        partial(
            parse_open_union,
            disc_key="type",
            variants=_OR_ANTHROPIC_NULLABLE_CALLER_VARIANTS,
            unknown_cls=UnknownORAnthropicNullableCaller,
            union_name="ORAnthropicNullableCaller",
        )
    ),
]
