"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .toolcallstatus import ToolCallStatus
from openrouter.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
    UnrecognizedStr,
)
from pydantic import model_serializer
from typing import Any, Literal, Optional, Union
from typing_extensions import NotRequired, TypedDict


ActionEnum = Union[
    Literal[
        "read",
        "write",
        "delete",
    ],
    UnrecognizedStr,
]


OutputMemoryServerToolItemType = Literal["openrouter:memory",]


class OutputMemoryServerToolItemTypedDict(TypedDict):
    r"""An openrouter:memory server tool output item"""

    status: ToolCallStatus
    type: OutputMemoryServerToolItemType
    action: NotRequired[ActionEnum]
    id: NotRequired[str]
    key: NotRequired[str]
    value: NotRequired[Nullable[Any]]


class OutputMemoryServerToolItem(BaseModel):
    r"""An openrouter:memory server tool output item"""

    status: ToolCallStatus

    type: OutputMemoryServerToolItemType

    action: Optional[ActionEnum] = None

    id: Optional[str] = None

    key: Optional[str] = None

    value: OptionalNullable[Any] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["action", "id", "key", "value"])
        nullable_fields = set(["value"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
