"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .applypatchcalloperation import (
    ApplyPatchCallOperation,
    ApplyPatchCallOperationTypedDict,
)
from .failabletoolcallstatus import FailableToolCallStatus
from openrouter.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Literal, Optional
from typing_extensions import NotRequired, TypedDict


OutputApplyPatchServerToolItemType = Literal["openrouter:apply_patch",]


class OutputApplyPatchServerToolItemTypedDict(TypedDict):
    r"""An openrouter:apply_patch server tool output item. The turn halts when validation succeeds so the client can apply the patch and echo an `apply_patch_call_output` on the next turn."""

    status: FailableToolCallStatus
    type: OutputApplyPatchServerToolItemType
    call_id: NotRequired[str]
    error: NotRequired[str]
    r"""The error message when the tool call failed before producing a result. Set together with `status: 'failed'`; absent on a successful call."""
    id: NotRequired[str]
    operation: NotRequired[ApplyPatchCallOperationTypedDict]
    r"""The patch operation requested by an `apply_patch_call`. `create_file` and `update_file` carry a V4A diff; `delete_file` omits it."""


class OutputApplyPatchServerToolItem(BaseModel):
    r"""An openrouter:apply_patch server tool output item. The turn halts when validation succeeds so the client can apply the patch and echo an `apply_patch_call_output` on the next turn."""

    status: FailableToolCallStatus

    type: OutputApplyPatchServerToolItemType

    call_id: Optional[str] = None

    error: Optional[str] = None
    r"""The error message when the tool call failed before producing a result. Set together with `status: 'failed'`; absent on a successful call."""

    id: Optional[str] = None

    operation: Optional[ApplyPatchCallOperation] = None
    r"""The patch operation requested by an `apply_patch_call`. `create_file` and `update_file` carry a V4A diff; `delete_file` omits it."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["call_id", "error", "id", "operation"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
