"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openrouter.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Literal, Optional
from typing_extensions import NotRequired, TypedDict


ParetoRouterPluginID = Literal["pareto-router",]


class ParetoRouterPluginTypedDict(TypedDict):
    id: ParetoRouterPluginID
    enabled: NotRequired[bool]
    r"""Set to false to disable the pareto-router plugin for this request. Defaults to true."""
    min_coding_score: NotRequired[float]
    r"""Minimum desired coding score between 0 and 1, where 1 is best. Higher values select from stronger coding models (sourced from Artificial Analysis coding percentiles). Maps internally to one of three tiers (low, medium, high). Omit to use the router default tier."""


class ParetoRouterPlugin(BaseModel):
    id: ParetoRouterPluginID

    enabled: Optional[bool] = None
    r"""Set to false to disable the pareto-router plugin for this request. Defaults to true."""

    min_coding_score: Optional[float] = None
    r"""Minimum desired coding score between 0 and 1, where 1 is best. Higher values select from stronger coding models (sourced from Artificial Analysis coding percentiles). Maps internally to one of three tiers (low, medium, high). Omit to use the router default tier."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["enabled", "min_coding_score"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
