"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openrouter.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class PercentileLatencyCutoffsTypedDict(TypedDict):
    r"""Percentile-based latency cutoffs. All specified cutoffs must be met for an endpoint to be preferred."""

    p50: NotRequired[float]
    r"""Maximum p50 latency (seconds)"""
    p75: NotRequired[float]
    r"""Maximum p75 latency (seconds)"""
    p90: NotRequired[float]
    r"""Maximum p90 latency (seconds)"""
    p99: NotRequired[float]
    r"""Maximum p99 latency (seconds)"""


class PercentileLatencyCutoffs(BaseModel):
    r"""Percentile-based latency cutoffs. All specified cutoffs must be met for an endpoint to be preferred."""

    p50: Optional[float] = None
    r"""Maximum p50 latency (seconds)"""

    p75: Optional[float] = None
    r"""Maximum p75 latency (seconds)"""

    p90: Optional[float] = None
    r"""Maximum p90 latency (seconds)"""

    p99: Optional[float] = None
    r"""Maximum p99 latency (seconds)"""
