"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openrouter.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class PercentileThroughputCutoffsTypedDict(TypedDict):
    r"""Percentile-based throughput cutoffs. All specified cutoffs must be met for an endpoint to be preferred."""

    p50: NotRequired[float]
    r"""Minimum p50 throughput (tokens/sec)"""
    p75: NotRequired[float]
    r"""Minimum p75 throughput (tokens/sec)"""
    p90: NotRequired[float]
    r"""Minimum p90 throughput (tokens/sec)"""
    p99: NotRequired[float]
    r"""Minimum p99 throughput (tokens/sec)"""


class PercentileThroughputCutoffs(BaseModel):
    r"""Percentile-based throughput cutoffs. All specified cutoffs must be met for an endpoint to be preferred."""

    p50: Optional[float] = None
    r"""Minimum p50 throughput (tokens/sec)"""

    p75: Optional[float] = None
    r"""Minimum p75 throughput (tokens/sec)"""

    p90: Optional[float] = None
    r"""Minimum p90 throughput (tokens/sec)"""

    p99: Optional[float] = None
    r"""Minimum p99 throughput (tokens/sec)"""
