"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .privateendpoint import PrivateEndpoint, PrivateEndpointTypedDict
from openrouter.types import BaseModel
from typing_extensions import TypedDict


class PrivateEndpointResponseTypedDict(TypedDict):
    data: PrivateEndpointTypedDict


class PrivateEndpointResponse(BaseModel):
    data: PrivateEndpoint
