"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openrouter.types import UnrecognizedStr
from typing import Literal, Union


PrivateEndpointCheckReason = Union[
    Literal[
        "database_error",
        "endpoint_limit_reached",
        "invalid_base_url",
        "model_not_found",
        "provider_not_found",
        "endpoint_not_found",
        "workspace_not_found",
        "no_byok_key",
        "key_decryption_failed",
        "upstream_error",
        "invalid_response",
        "invalid_stream",
        "missing_usage",
        "model_mismatch",
        "not_validated",
        "validation_stale",
    ],
    UnrecognizedStr,
]
r"""Why the check failed."""
