"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .privateendpointcheck import PrivateEndpointCheck, PrivateEndpointCheckTypedDict
from openrouter.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class PrivateEndpointValidationTypedDict(TypedDict):
    checks: List[PrivateEndpointCheckTypedDict]
    passed: bool
    r"""Whether every check passed."""


class PrivateEndpointValidation(BaseModel):
    checks: List[PrivateEndpointCheck]

    passed: bool
    r"""Whether every check passed."""
