"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .privateendpointcheckreason import PrivateEndpointCheckReason
from openrouter.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class PrivateEndpointCheckTypedDict(TypedDict):
    name: str
    r"""Check name."""
    passed: bool
    actual_model: NotRequired[Nullable[str]]
    r"""Model the upstream reported serving, when it differs from the request."""
    reason: NotRequired[PrivateEndpointCheckReason]
    r"""Why the check failed."""
    upstream_message: NotRequired[Nullable[str]]
    r"""Error message returned by your deployment when the call failed."""
    upstream_status: NotRequired[int]
    r"""HTTP status returned by your deployment when the call failed."""


class PrivateEndpointCheck(BaseModel):
    name: str
    r"""Check name."""

    passed: bool

    actual_model: OptionalNullable[str] = UNSET
    r"""Model the upstream reported serving, when it differs from the request."""

    reason: Optional[PrivateEndpointCheckReason] = None
    r"""Why the check failed."""

    upstream_message: OptionalNullable[str] = UNSET
    r"""Error message returned by your deployment when the call failed."""

    upstream_status: Optional[int] = None
    r"""HTTP status returned by your deployment when the call failed."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["actual_model", "reason", "upstream_message", "upstream_status"]
        )
        nullable_fields = set(["actual_model", "upstream_message"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
