"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openrouter.types import BaseModel
from typing_extensions import TypedDict


class PrivateEndpointActivationTypedDict(TypedDict):
    r"""Validate and activate in the same call. On a failed validation the draft is kept and returned with a 422, so fix it and call `/validate` and `/activate` instead of creating it again."""

    workspace_id: str
    r"""Workspace whose BYOK credential is used for the live validation call. The workspace must belong to your account."""


class PrivateEndpointActivation(BaseModel):
    r"""Validate and activate in the same call. On a failed validation the draft is kept and returned with a 422, so fix it and call `/validate` and `/activate` instead of creating it again."""

    workspace_id: str
    r"""Workspace whose BYOK credential is used for the live validation call. The workspace must belong to your account."""
