"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openrouter.types import BaseModel
from typing import Literal
from typing_extensions import TypedDict


PromptCacheBreakpointMode = Literal["explicit",]


class PromptCacheBreakpointTypedDict(TypedDict):
    r"""Marks an explicit prompt-cache boundary on this content block. Everything through the block carrying this marker is part of the candidate cached prefix. Only supported by OpenAI GPT-5.6 and newer."""

    mode: PromptCacheBreakpointMode


class PromptCacheBreakpoint(BaseModel):
    r"""Marks an explicit prompt-cache boundary on this content block. Everything through the block carrying this marker is part of the candidate cached prefix. Only supported by OpenAI GPT-5.6 and newer."""

    mode: PromptCacheBreakpointMode
