"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .servertoolexecutedby import ServerToolExecutedBy
from .servertoolprice import ServerToolPrice, ServerToolPriceTypedDict
from openrouter.types import BaseModel, Nullable, UNSET_SENTINEL, UnrecognizedStr
from pydantic import model_serializer
from typing import List, Literal, Union
from typing_extensions import TypedDict


BYOK = Union[
    Literal[
        "required",
        "optional",
        "none",
    ],
    UnrecognizedStr,
]
r"""Whether the engine needs the caller's own key, saved in plugin settings: `required` (OpenRouter holds none), `optional` (OpenRouter's key is used unless the caller saved one), or `none`"""


ServerToolEngineDataRegion = Union[
    Literal[
        "global",
        "europe",
        "us",
    ],
    UnrecognizedStr,
]


PricingSource = Union[
    Literal[
        "openrouter",
        "provider",
        "byok",
        "none",
    ],
    UnrecognizedStr,
]
r"""Who bills the engine's calls beyond the model's tokens: `openrouter` (the `pricing` rows, from the caller's credits), `provider` (a per-call tool fee from the model's provider on the inference call, at its own rates), `byok` (the engine's vendor, against the caller's own key), or `none` (no charge)"""


class ServerToolEngineTypedDict(TypedDict):
    byok: BYOK
    r"""Whether the engine needs the caller's own key, saved in plugin settings: `required` (OpenRouter holds none), `optional` (OpenRouter's key is used unless the caller saved one), or `none`"""
    data_regions: List[ServerToolEngineDataRegion]
    r"""The data regions whose requests this engine serves without leaving the region. A request pinned to a region can only use engines that list it; `global` is always listed."""
    default_mode: Nullable[str]
    r"""The `parameters.mode` a request without one runs and bills as; null for engines without modes. The `pricing[]` row with this `mode` is what an unmoded request bills"""
    executed_by: ServerToolExecutedBy
    r"""Who runs the tool call: the model provider during inference (`provider`), OpenRouter (`openrouter`), or the caller's application after the call is returned (`client`)."""
    id: Nullable[str]
    r"""The `parameters.engine` value that selects this engine; null for the single engine of a tool without an engine parameter"""
    name: str
    pricing: List[ServerToolPriceTypedDict]
    r"""The rows OpenRouter bills; non-empty exactly when `pricing_source` is `openrouter`"""
    pricing_doc_url: Nullable[str]
    r"""Where the rates are documented when `pricing_source` is `provider` or `byok`; null otherwise"""
    pricing_source: PricingSource
    r"""Who bills the engine's calls beyond the model's tokens: `openrouter` (the `pricing` rows, from the caller's credits), `provider` (a per-call tool fee from the model's provider on the inference call, at its own rates), `byok` (the engine's vendor, against the caller's own key), or `none` (no charge)"""


class ServerToolEngine(BaseModel):
    byok: BYOK
    r"""Whether the engine needs the caller's own key, saved in plugin settings: `required` (OpenRouter holds none), `optional` (OpenRouter's key is used unless the caller saved one), or `none`"""

    data_regions: List[ServerToolEngineDataRegion]
    r"""The data regions whose requests this engine serves without leaving the region. A request pinned to a region can only use engines that list it; `global` is always listed."""

    default_mode: Nullable[str]
    r"""The `parameters.mode` a request without one runs and bills as; null for engines without modes. The `pricing[]` row with this `mode` is what an unmoded request bills"""

    executed_by: ServerToolExecutedBy
    r"""Who runs the tool call: the model provider during inference (`provider`), OpenRouter (`openrouter`), or the caller's application after the call is returned (`client`)."""

    id: Nullable[str]
    r"""The `parameters.engine` value that selects this engine; null for the single engine of a tool without an engine parameter"""

    name: str

    pricing: List[ServerToolPrice]
    r"""The rows OpenRouter bills; non-empty exactly when `pricing_source` is `openrouter`"""

    pricing_doc_url: Nullable[str]
    r"""Where the rates are documented when `pricing_source` is `provider` or `byok`; null otherwise"""

    pricing_source: PricingSource
    r"""Who bills the engine's calls beyond the model's tokens: `openrouter` (the `pricing` rows, from the caller's credits), `provider` (a per-call tool fee from the model's provider on the inference call, at its own rates), `byok` (the engine's vendor, against the caller's own key), or `none` (no charge)"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m
