"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .servertooloutputname import ServerToolOutputName, ServerToolOutputNameTypedDict
from openrouter.types import BaseModel, UnrecognizedStr
from typing import List, Literal, Union
from typing_extensions import TypedDict


ServerToolInputNameAPIFormat = Union[
    Literal[
        "responses",
        "chat-completions",
        "anthropic-messages",
    ],
    UnrecognizedStr,
]


class ServerToolInputNameTypedDict(TypedDict):
    api_formats: List[ServerToolInputNameAPIFormat]
    r"""API formats that accept this spelling in `tools[].type`"""
    output_names: List[ServerToolOutputNameTypedDict]
    r"""What the call surfaces as on each accepting API format when requested under this spelling; a format is absent when the call is not visible to the caller"""
    type: str


class ServerToolInputName(BaseModel):
    api_formats: List[ServerToolInputNameAPIFormat]
    r"""API formats that accept this spelling in `tools[].type`"""

    output_names: List[ServerToolOutputName]
    r"""What the call surfaces as on each accepting API format when requested under this spelling; a format is absent when the call is not visible to the caller"""

    type: str
