"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openrouter.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class ServerToolNativeModelTypedDict(TypedDict):
    providers: List[str]
    slug: str


class ServerToolNativeModel(BaseModel):
    providers: List[str]

    slug: str
