"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openrouter.types import BaseModel, UNSET_SENTINEL, UnrecognizedStr
from pydantic import model_serializer
from typing import Literal, Optional, Union
from typing_extensions import NotRequired, TypedDict


ServerToolOutputNameAPIFormat = Union[
    Literal[
        "responses",
        "chat-completions",
        "anthropic-messages",
    ],
    UnrecognizedStr,
]


class ServerToolOutputNameTypedDict(TypedDict):
    api_format: ServerToolOutputNameAPIFormat
    type: str
    r"""Output item `type` on Responses, content block `type` on Anthropic Messages, `reasoning_details[].type` on Chat Completions"""
    name: NotRequired[str]
    r"""Anthropic Messages `server_tool_use` block `name`, when the call surfaces as one"""


class ServerToolOutputName(BaseModel):
    api_format: ServerToolOutputNameAPIFormat

    type: str
    r"""Output item `type` on Responses, content block `type` on Anthropic Messages, `reasoning_details[].type` on Chat Completions"""

    name: Optional[str] = None
    r"""Anthropic Messages `server_tool_use` block `name`, when the call surfaces as one"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["name"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
