"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openrouter.types import BaseModel
from typing_extensions import TypedDict


class ServerToolNativeSupportTypedDict(TypedDict):
    r"""Endpoints whose provider runs this tool itself during inference. Zero for tools no provider runs natively."""

    endpoint_count: int
    model_count: int


class ServerToolNativeSupport(BaseModel):
    r"""Endpoints whose provider runs this tool itself during inference. Zero for tools no provider runs natively."""

    endpoint_count: int

    model_count: int
