"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openrouter.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
    UnrecognizedStr,
)
from pydantic import model_serializer
from typing import Any, List, Literal, Union
from typing_extensions import NotRequired, TypedDict


class ShellCallItemActionTypedDict(TypedDict):
    commands: List[str]
    max_output_length: NotRequired[Nullable[int]]
    timeout_ms: NotRequired[Nullable[int]]


class ShellCallItemAction(BaseModel):
    commands: List[str]

    max_output_length: OptionalNullable[int] = UNSET

    timeout_ms: OptionalNullable[int] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["max_output_length", "timeout_ms"])
        nullable_fields = set(["max_output_length", "timeout_ms"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


ShellCallItemStatus = Union[
    Literal[
        "in_progress",
        "completed",
        "incomplete",
    ],
    UnrecognizedStr,
]


ShellCallItemType = Literal["shell_call",]


class ShellCallItemTypedDict(TypedDict):
    r"""A shell command execution call (newer variant)"""

    action: ShellCallItemActionTypedDict
    call_id: str
    type: ShellCallItemType
    environment: NotRequired[Nullable[Any]]
    id: NotRequired[Nullable[str]]
    status: NotRequired[Nullable[ShellCallItemStatus]]


class ShellCallItem(BaseModel):
    r"""A shell command execution call (newer variant)"""

    action: ShellCallItemAction

    call_id: str

    type: ShellCallItemType

    environment: OptionalNullable[Any] = UNSET

    id: OptionalNullable[str] = UNSET

    status: OptionalNullable[ShellCallItemStatus] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["environment", "id", "status"])
        nullable_fields = set(["environment", "id", "status"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
