"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openrouter.types import BaseModel
import pydantic
from typing_extensions import Annotated, TypedDict


class SignInternDaemonResponseTypedDict(TypedDict):
    r"""Headers the CLI copies onto the daemon request so the sidecar can verify who is asking."""

    x_ori_invoke_signature: str
    r"""Base64 Ed25519 signature over the intern id, timestamp, user and body digest."""
    x_ori_invoke_timestamp: str
    r"""Unix seconds at signing; the daemon refuses proofs older than its window."""
    x_ori_invoke_user: str
    r"""The verified OAuth subject the proof names. Never taken from the request."""


class SignInternDaemonResponse(BaseModel):
    r"""Headers the CLI copies onto the daemon request so the sidecar can verify who is asking."""

    x_ori_invoke_signature: Annotated[
        str, pydantic.Field(alias="x-ori-invoke-signature")
    ]
    r"""Base64 Ed25519 signature over the intern id, timestamp, user and body digest."""

    x_ori_invoke_timestamp: Annotated[
        str, pydantic.Field(alias="x-ori-invoke-timestamp")
    ]
    r"""Unix seconds at signing; the daemon refuses proofs older than its window."""

    x_ori_invoke_user: Annotated[str, pydantic.Field(alias="x-ori-invoke-user")]
    r"""The verified OAuth subject the proof names. Never taken from the request."""


try:
    SignInternDaemonResponse.model_rebuild()
except NameError:
    pass
