"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .provideroptions import ProviderOptions, ProviderOptionsTypedDict
from .speechinputreference import SpeechInputReference, SpeechInputReferenceTypedDict
from .traceconfig import TraceConfig, TraceConfigTypedDict
from openrouter.types import BaseModel, UNSET_SENTINEL, UnrecognizedStr
from pydantic import model_serializer
from typing import List, Literal, Optional, Union
from typing_extensions import NotRequired, TypedDict


class SpeechRequestProviderTypedDict(TypedDict):
    r"""Provider-specific passthrough configuration"""

    options: NotRequired[ProviderOptionsTypedDict]
    r"""Provider-specific options keyed by provider slug. Only options for the matched provider are forwarded; the rest are ignored. Unrecognized keys are silently dropped."""


class SpeechRequestProvider(BaseModel):
    r"""Provider-specific passthrough configuration"""

    options: Optional[ProviderOptions] = None
    r"""Provider-specific options keyed by provider slug. Only options for the matched provider are forwarded; the rest are ignored. Unrecognized keys are silently dropped."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["options"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


SpeechRequestResponseFormat = Union[
    Literal[
        "mp3",
        "pcm",
    ],
    UnrecognizedStr,
]
r"""Audio output format"""


class SpeechRequestTypedDict(TypedDict):
    r"""Text-to-speech request input"""

    input: str
    r"""Text to synthesize"""
    model: str
    r"""TTS model identifier"""
    input_references: NotRequired[List[SpeechInputReferenceTypedDict]]
    r"""Reference content for stateless voice cloning: one `input_audio` part carrying the voice sample, optionally accompanied by one `text` part with its transcript. Only routed to endpoints that support voice cloning."""
    provider: NotRequired[SpeechRequestProviderTypedDict]
    r"""Provider-specific passthrough configuration"""
    response_format: NotRequired[SpeechRequestResponseFormat]
    r"""Audio output format"""
    session_id: NotRequired[str]
    r"""A unique identifier for grouping related requests (e.g., a conversation or agent workflow). Used for observability grouping in Broadcast and private logging; never sent to the provider. If provided in both the request body and the x-session-id header, the body value takes precedence. Maximum of 256 characters."""
    speed: NotRequired[float]
    r"""Playback speed multiplier. Only used by models that support it (e.g. OpenAI TTS). Ignored by other providers."""
    trace: NotRequired[TraceConfigTypedDict]
    r"""Metadata for observability and tracing. Known keys (trace_id, trace_name, span_name, generation_name, parent_span_id) have special handling. Additional keys are passed through as custom metadata to configured broadcast destinations."""
    user: NotRequired[str]
    r"""A unique identifier representing your end-user. Forwarded to Broadcast and private logging as the end-user id; never sent to the provider."""
    voice: NotRequired[str]
    r"""Voice identifier (provider-specific)."""


class SpeechRequest(BaseModel):
    r"""Text-to-speech request input"""

    input: str
    r"""Text to synthesize"""

    model: str
    r"""TTS model identifier"""

    input_references: Optional[List[SpeechInputReference]] = None
    r"""Reference content for stateless voice cloning: one `input_audio` part carrying the voice sample, optionally accompanied by one `text` part with its transcript. Only routed to endpoints that support voice cloning."""

    provider: Optional[SpeechRequestProvider] = None
    r"""Provider-specific passthrough configuration"""

    response_format: Optional[SpeechRequestResponseFormat] = "pcm"
    r"""Audio output format"""

    session_id: Optional[str] = None
    r"""A unique identifier for grouping related requests (e.g., a conversation or agent workflow). Used for observability grouping in Broadcast and private logging; never sent to the provider. If provided in both the request body and the x-session-id header, the body value takes precedence. Maximum of 256 characters."""

    speed: Optional[float] = None
    r"""Playback speed multiplier. Only used by models that support it (e.g. OpenAI TTS). Ignored by other providers."""

    trace: Optional[TraceConfig] = None
    r"""Metadata for observability and tracing. Known keys (trace_id, trace_name, span_name, generation_name, parent_span_id) have special handling. Additional keys are passed through as custom metadata to configured broadcast destinations."""

    user: Optional[str] = None
    r"""A unique identifier representing your end-user. Forwarded to Broadcast and private logging as the end-user id; never sent to the provider."""

    voice: Optional[str] = None
    r"""Voice identifier (provider-specific)."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "input_references",
                "provider",
                "response_format",
                "session_id",
                "speed",
                "trace",
                "user",
                "voice",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
