"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .speechturn import SpeechTurn, SpeechTurnTypedDict
from typing import List, Union
from typing_extensions import TypeAliasType


SpeechInputTypedDict = TypeAliasType(
    "SpeechInputTypedDict", Union[str, List[SpeechTurnTypedDict]]
)
r"""Text to synthesize, or a list of turns for multi-speaker input. Each turn has its own text, voice, and instructions. Multi-speaker input is currently supported by Gemini TTS models only."""


SpeechInput = TypeAliasType("SpeechInput", Union[str, List[SpeechTurn]])
r"""Text to synthesize, or a list of turns for multi-speaker input. Each turn has its own text, voice, and instructions. Multi-speaker input is currently supported by Gemini TTS models only."""
