"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openrouter.types import BaseModel
from typing_extensions import TypedDict


class SpeechInputReferenceImageInputTypedDict(TypedDict):
    r"""Reference image input object"""

    url: str
    r"""JPEG, PNG, or WebP reference image as a base64 data URI or a public http(s) URL. Remote images are downloaded (15 MiB max) and forwarded as bytes, never as the URL."""


class SpeechInputReferenceImageInput(BaseModel):
    r"""Reference image input object"""

    url: str
    r"""JPEG, PNG, or WebP reference image as a base64 data URI or a public http(s) URL. Remote images are downloaded (15 MiB max) and forwarded as bytes, never as the URL."""
