"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openrouter.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class SpeechInputReferenceAudioInputTypedDict(TypedDict):
    r"""Reference audio input object"""

    data: NotRequired[str]
    r"""Base64-encoded reference audio (optionally a data URI). Supported audio formats are provider-specific. Limited to 20 MiB of base64 (15 MiB of decoded audio). Exactly one of `data` or `url` is required."""
    format_: NotRequired[str]
    r"""Audio format of the reference audio (e.g., wav, mp3). Optional; most providers detect the format from the audio bytes."""
    url: NotRequired[str]
    r"""Public http(s) URL of the reference audio. OpenRouter downloads it (15 MiB max) and forwards the bytes, never the URL. Exactly one of `data` or `url` is required."""


class SpeechInputReferenceAudioInput(BaseModel):
    r"""Reference audio input object"""

    data: Optional[str] = None
    r"""Base64-encoded reference audio (optionally a data URI). Supported audio formats are provider-specific. Limited to 20 MiB of base64 (15 MiB of decoded audio). Exactly one of `data` or `url` is required."""

    format_: Annotated[Optional[str], pydantic.Field(alias="format")] = None
    r"""Audio format of the reference audio (e.g., wav, mp3). Optional; most providers detect the format from the audio bytes."""

    url: Optional[str] = None
    r"""Public http(s) URL of the reference audio. OpenRouter downloads it (15 MiB max) and forwards the bytes, never the URL. Exactly one of `data` or `url` is required."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["data", "format", "url"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    SpeechInputReferenceAudioInput.model_rebuild()
except NameError:
    pass
