"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openrouter.types import BaseModel
from typing_extensions import TypedDict


class STTEntityTypedDict(TypedDict):
    r"""A detected entity, returned when the provider runs entity detection"""

    end_char: int
    r"""Zero-based exclusive character offset of the entity end within the response-level text (not seconds)"""
    start_char: int
    r"""Zero-based character offset of the entity start within the response-level text (not seconds)"""
    text: str
    r"""Entity text as it appears in the transcript"""
    type: str
    r"""Provider entity type label"""


class STTEntity(BaseModel):
    r"""A detected entity, returned when the provider runs entity detection"""

    end_char: int
    r"""Zero-based exclusive character offset of the entity end within the response-level text (not seconds)"""

    start_char: int
    r"""Zero-based character offset of the entity start within the response-level text (not seconds)"""

    text: str
    r"""Entity text as it appears in the transcript"""

    type: str
    r"""Provider entity type label"""
