"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openrouter.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class STTURLInputAudioTypedDict(TypedDict):
    r"""Audio input fetched by the provider from a URL"""

    url: str
    r"""Publicly reachable http(s) URL of the audio file. The provider downloads it directly, so the inline upload size limit does not apply. Only supported by some providers."""
    format_: NotRequired[str]
    r"""Audio format of the file at the URL. Defaults to the extension of the URL path; required when the path has no extension."""


class STTURLInputAudio(BaseModel):
    r"""Audio input fetched by the provider from a URL"""

    url: str
    r"""Publicly reachable http(s) URL of the audio file. The provider downloads it directly, so the inline upload size limit does not apply. Only supported by some providers."""

    format_: Annotated[Optional[str], pydantic.Field(alias="format")] = None
    r"""Audio format of the file at the URL. Defaults to the extension of the URL path; required when the path has no extension."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["format"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    STTURLInputAudio.model_rebuild()
except NameError:
    pass
