"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openrouter.types import BaseModel, UNSET_SENTINEL, UnrecognizedStr
from pydantic import model_serializer
from typing import Literal, Optional, Union
from typing_extensions import NotRequired, TypedDict


Algorithm = Union[
    Literal[
        "capability",
        "stage",
        "auto",
        "random",
        "composite",
        "passthrough",
    ],
    UnrecognizedStr,
]
r"""Routing algorithm for this request. \"capability\" calls a small judge model to rate how demanding the task is, then picks the efficient or capable candidate. \"stage\" reads the tool-result history (errors, repeated failures, edits landing) and calls the judge only when those signals are undecided. \"auto\" is \"stage\" without the judge call. \"random\" picks one candidate at random. \"composite\" keeps the tier chosen on the last human turn and re-evaluates tool turns with the stage signals. \"passthrough\" serves the eligible candidates in the order OpenRouter already ranked them, with no routing decision and no judge call. Omit this field to use the platform default, capability."""


SwitchyardRouterPluginID = Literal["switchyard-router",]


class SwitchyardRouterPluginTypedDict(TypedDict):
    id: SwitchyardRouterPluginID
    algorithm: NotRequired[Algorithm]
    r"""Routing algorithm for this request. \"capability\" calls a small judge model to rate how demanding the task is, then picks the efficient or capable candidate. \"stage\" reads the tool-result history (errors, repeated failures, edits landing) and calls the judge only when those signals are undecided. \"auto\" is \"stage\" without the judge call. \"random\" picks one candidate at random. \"composite\" keeps the tier chosen on the last human turn and re-evaluates tool turns with the stage signals. \"passthrough\" serves the eligible candidates in the order OpenRouter already ranked them, with no routing decision and no judge call. Omit this field to use the platform default, capability."""


class SwitchyardRouterPlugin(BaseModel):
    id: SwitchyardRouterPluginID

    algorithm: Optional[Algorithm] = None
    r"""Routing algorithm for this request. \"capability\" calls a small judge model to rate how demanding the task is, then picks the efficient or capable candidate. \"stage\" reads the tool-result history (errors, repeated failures, edits landing) and calls the judge only when those signals are undecided. \"auto\" is \"stage\" without the judge call. \"random\" picks one candidate at random. \"composite\" keeps the tier chosen on the last human turn and re-evaluates tool turns with the stage signals. \"passthrough\" serves the eligible candidates in the order OpenRouter already ranked them, with no routing decision and no judge call. Omit this field to use the platform default, capability."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["algorithm"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
