"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openrouter.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
    UnrecognizedStr,
)
from pydantic import model_serializer
from typing import Any, Literal, Optional, Union
from typing_extensions import NotRequired, TypedDict


ToolSearchCallItemExecution = Union[
    Literal[
        "server",
        "client",
    ],
    UnrecognizedStr,
]


ToolSearchCallItemStatus = Union[
    Literal[
        "in_progress",
        "completed",
        "incomplete",
    ],
    UnrecognizedStr,
]


ToolSearchCallItemType = Literal["tool_search_call",]


class ToolSearchCallItemTypedDict(TypedDict):
    r"""A tool search call the client executed"""

    call_id: str
    execution: ToolSearchCallItemExecution
    type: ToolSearchCallItemType
    arguments: NotRequired[Any]
    id: NotRequired[Nullable[str]]
    status: NotRequired[Nullable[ToolSearchCallItemStatus]]


class ToolSearchCallItem(BaseModel):
    r"""A tool search call the client executed"""

    call_id: str

    execution: ToolSearchCallItemExecution

    type: ToolSearchCallItemType

    arguments: Optional[Any] = None

    id: OptionalNullable[str] = UNSET

    status: OptionalNullable[ToolSearchCallItemStatus] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["arguments", "id", "status"])
        nullable_fields = set(["id", "status"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
