"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .privateendpointpricing import (
    PrivateEndpointPricing,
    PrivateEndpointPricingTypedDict,
)
from openrouter.types import BaseModel
from typing_extensions import TypedDict


class UpdatePrivateEndpointPricingRequestTypedDict(TypedDict):
    pricing: PrivateEndpointPricingTypedDict
    r"""Negotiated per-token rates reported for requests routed to this endpoint."""


class UpdatePrivateEndpointPricingRequest(BaseModel):
    pricing: PrivateEndpointPricing
    r"""Negotiated per-token rates reported for requests routed to this endpoint."""
