"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openrouter.types import BaseModel
from typing_extensions import TypedDict


class ValidatePrivateEndpointRequestTypedDict(TypedDict):
    workspace_id: str
    r"""Workspace whose BYOK credential is used for the live validation call. The workspace must belong to your account."""


class ValidatePrivateEndpointRequest(BaseModel):
    workspace_id: str
    r"""Workspace whose BYOK credential is used for the live validation call. The workspace must belong to your account."""
