"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openrouter.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class VaultSecretWriteRequestTypedDict(TypedDict):
    r"""Secret value and the exact hostnames it may be released to."""

    hosts: List[str]
    r"""Exact DNS hostnames the secret may be sent to, 1 to 100 entries. Each entry is lowercased and a trailing dot is removed, so `API.Example.com.` is stored as `api.example.com`. Schemes, ports, paths, wildcards and empty values are rejected. Duplicates after normalization are collapsed. Matching is exact: a secret bound to `api.example.com` is never released to `example.com` or any other hostname."""
    value: str
    r"""Secret value, 1 to 65536 characters. It is encrypted at rest and never returned."""


class VaultSecretWriteRequest(BaseModel):
    r"""Secret value and the exact hostnames it may be released to."""

    hosts: List[str]
    r"""Exact DNS hostnames the secret may be sent to, 1 to 100 entries. Each entry is lowercased and a trailing dot is removed, so `API.Example.com.` is stored as `api.example.com`. Schemes, ports, paths, wildcards and empty values are rejected. Duplicates after normalization are collapsed. Matching is exact: a secret bound to `api.example.com` is never released to `example.com` or any other hostname."""

    value: str
    r"""Secret value, 1 to 65536 characters. It is encrypted at rest and never returned."""
