"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from openrouter.types import BaseModel, Nullable, UNSET_SENTINEL, UnrecognizedStr
from pydantic import model_serializer
from typing import List, Literal, Union
from typing_extensions import TypedDict


VaultEffectiveSecretScope = Union[
    Literal[
        "intern",
        "attached",
        "workspace",
    ],
    UnrecognizedStr,
]
r"""Where the delivered secret is stored: `intern` for the intern's own vault, `attached` for a vault attached to the intern, `workspace` for the workspace vault."""


class VaultEffectiveSecretTypedDict(TypedDict):
    r"""Metadata for the one secret the intern's outbound requests receive under this name. The secret value is never returned. The intern receives it only on requests to a hostname in `hosts`, or on any request when `hosts` is `null`; a request to any other hostname receives no secret under this name, even when another vault holds one. `fingerprint` is comparable only within one vault."""

    created_at: datetime
    fingerprint: Nullable[str]
    hosts: Nullable[List[str]]
    name: str
    scope: VaultEffectiveSecretScope
    r"""Where the delivered secret is stored: `intern` for the intern's own vault, `attached` for a vault attached to the intern, `workspace` for the workspace vault."""


class VaultEffectiveSecret(BaseModel):
    r"""Metadata for the one secret the intern's outbound requests receive under this name. The secret value is never returned. The intern receives it only on requests to a hostname in `hosts`, or on any request when `hosts` is `null`; a request to any other hostname receives no secret under this name, even when another vault holds one. `fingerprint` is comparable only within one vault."""

    created_at: datetime

    fingerprint: Nullable[str]

    hosts: Nullable[List[str]]

    name: str

    scope: VaultEffectiveSecretScope
    r"""Where the delivered secret is stored: `intern` for the intern's own vault, `attached` for a vault attached to the intern, `workspace` for the workspace vault."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m
