"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .vaultsecret import VaultSecret, VaultSecretTypedDict
from openrouter.types import BaseModel
from typing_extensions import TypedDict


class VaultSecretResponseTypedDict(TypedDict):
    r"""Metadata for the stored secret."""

    data: VaultSecretTypedDict
    r"""Metadata for one stored secret. The secret value is never returned. `fingerprint` is a keyed SHA-256 digest of the value: equal fingerprints within one scope mean equal values, but a workspace secret and its intern copy carry different fingerprints. `hosts` and `fingerprint` are `null` only for legacy rows written before host binding was required; storing the secret again assigns hosts."""


class VaultSecretResponse(BaseModel):
    r"""Metadata for the stored secret."""

    data: VaultSecret
    r"""Metadata for one stored secret. The secret value is never returned. `fingerprint` is a keyed SHA-256 digest of the value: equal fingerprints within one scope mean equal values, but a workspace secret and its intern copy carry different fingerprints. `hosts` and `fingerprint` are `null` only for legacy rows written before host binding was required; storing the secret again assigns hosts."""
