"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openrouter.types import BaseModel, UnrecognizedStr
from openrouter.utils import validate_open_enum
from pydantic.functional_validators import PlainValidator
from typing import List, Literal, Optional, Union
from typing_extensions import Annotated, NotRequired, TypedDict


WebSearchShorthandType = Union[
    Literal[
        "web_search",
        "web_search_preview",
        "web_search_preview_2025_03_11",
        "web_search_2025_08_26",
    ],
    UnrecognizedStr,
]


WebSearchShorthandEngine = Union[
    Literal[
        "auto",
        "native",
        "exa",
    ],
    UnrecognizedStr,
]
r"""Which search engine to use. \"auto\" (default) uses native if the provider supports it, otherwise Exa. \"native\" forces the provider's built-in search (parameters like max_results, search_context_size, and domain filters are not forwarded to the provider). \"exa\" forces the Exa search API."""


WebSearchShorthandSearchContextSize = Union[
    Literal[
        "low",
        "medium",
        "high",
    ],
    UnrecognizedStr,
]
r"""How much context to retrieve per result. Defaults to medium (15000 chars). Only applies when using the Exa engine; ignored with native provider search."""


WebSearchShorthandTypeApproximate = Literal["approximate",]


class WebSearchShorthandUserLocationTypedDict(TypedDict):
    r"""Approximate user location for location-biased results."""

    type: NotRequired[WebSearchShorthandTypeApproximate]
    city: NotRequired[str]
    region: NotRequired[str]
    country: NotRequired[str]
    timezone: NotRequired[str]


class WebSearchShorthandUserLocation(BaseModel):
    r"""Approximate user location for location-biased results."""

    type: Optional[WebSearchShorthandTypeApproximate] = None

    city: Optional[str] = None

    region: Optional[str] = None

    country: Optional[str] = None

    timezone: Optional[str] = None


WebSearchShorthandParametersEngine = Union[
    Literal[
        "auto",
        "native",
        "exa",
    ],
    UnrecognizedStr,
]
r"""Which search engine to use. \"auto\" (default) uses native if the provider supports it, otherwise Exa. \"native\" forces the provider's built-in search (parameters like max_results, search_context_size, and domain filters are not forwarded to the provider). \"exa\" forces the Exa search API."""


WebSearchShorthandParametersSearchContextSize = Union[
    Literal[
        "low",
        "medium",
        "high",
    ],
    UnrecognizedStr,
]
r"""How much context to retrieve per result. Defaults to medium (15000 chars). Only applies when using the Exa engine; ignored with native provider search."""


WebSearchShorthandParametersType = Literal["approximate",]


class WebSearchShorthandParametersUserLocationTypedDict(TypedDict):
    r"""Approximate user location for location-biased results."""

    type: NotRequired[WebSearchShorthandParametersType]
    city: NotRequired[str]
    region: NotRequired[str]
    country: NotRequired[str]
    timezone: NotRequired[str]


class WebSearchShorthandParametersUserLocation(BaseModel):
    r"""Approximate user location for location-biased results."""

    type: Optional[WebSearchShorthandParametersType] = None

    city: Optional[str] = None

    region: Optional[str] = None

    country: Optional[str] = None

    timezone: Optional[str] = None


class WebSearchShorthandParametersTypedDict(TypedDict):
    engine: NotRequired[WebSearchShorthandParametersEngine]
    r"""Which search engine to use. \"auto\" (default) uses native if the provider supports it, otherwise Exa. \"native\" forces the provider's built-in search (parameters like max_results, search_context_size, and domain filters are not forwarded to the provider). \"exa\" forces the Exa search API."""
    max_results: NotRequired[float]
    r"""Maximum number of search results to return per search call. Defaults to 5. Only applies when using the Exa engine; ignored with native provider search."""
    max_total_results: NotRequired[float]
    r"""Maximum total number of search results across all search calls in a single request. Once this limit is reached, the tool will stop returning new results. Useful for controlling cost and context size in agentic loops."""
    search_context_size: NotRequired[WebSearchShorthandParametersSearchContextSize]
    r"""How much context to retrieve per result. Defaults to medium (15000 chars). Only applies when using the Exa engine; ignored with native provider search."""
    user_location: NotRequired[WebSearchShorthandParametersUserLocationTypedDict]
    r"""Approximate user location for location-biased results."""
    allowed_domains: NotRequired[List[str]]
    r"""Limit search results to these domains. Only applies when using the Exa engine; ignored with native provider search."""
    excluded_domains: NotRequired[List[str]]
    r"""Exclude search results from these domains. Only applies when using the Exa engine; ignored with native provider search."""


class WebSearchShorthandParameters(BaseModel):
    engine: Annotated[
        Optional[WebSearchShorthandParametersEngine],
        PlainValidator(validate_open_enum(False)),
    ] = None
    r"""Which search engine to use. \"auto\" (default) uses native if the provider supports it, otherwise Exa. \"native\" forces the provider's built-in search (parameters like max_results, search_context_size, and domain filters are not forwarded to the provider). \"exa\" forces the Exa search API."""

    max_results: Optional[float] = None
    r"""Maximum number of search results to return per search call. Defaults to 5. Only applies when using the Exa engine; ignored with native provider search."""

    max_total_results: Optional[float] = None
    r"""Maximum total number of search results across all search calls in a single request. Once this limit is reached, the tool will stop returning new results. Useful for controlling cost and context size in agentic loops."""

    search_context_size: Annotated[
        Optional[WebSearchShorthandParametersSearchContextSize],
        PlainValidator(validate_open_enum(False)),
    ] = None
    r"""How much context to retrieve per result. Defaults to medium (15000 chars). Only applies when using the Exa engine; ignored with native provider search."""

    user_location: Optional[WebSearchShorthandParametersUserLocation] = None
    r"""Approximate user location for location-biased results."""

    allowed_domains: Optional[List[str]] = None
    r"""Limit search results to these domains. Only applies when using the Exa engine; ignored with native provider search."""

    excluded_domains: Optional[List[str]] = None
    r"""Exclude search results from these domains. Only applies when using the Exa engine; ignored with native provider search."""


class WebSearchShorthandTypedDict(TypedDict):
    r"""Web search tool using OpenAI Responses API syntax. Automatically converted to openrouter:web_search."""

    type: WebSearchShorthandType
    engine: NotRequired[WebSearchShorthandEngine]
    r"""Which search engine to use. \"auto\" (default) uses native if the provider supports it, otherwise Exa. \"native\" forces the provider's built-in search (parameters like max_results, search_context_size, and domain filters are not forwarded to the provider). \"exa\" forces the Exa search API."""
    max_results: NotRequired[float]
    r"""Maximum number of search results to return per search call. Defaults to 5. Only applies when using the Exa engine; ignored with native provider search."""
    max_total_results: NotRequired[float]
    r"""Maximum total number of search results across all search calls in a single request. Once this limit is reached, the tool will stop returning new results. Useful for controlling cost and context size in agentic loops."""
    search_context_size: NotRequired[WebSearchShorthandSearchContextSize]
    r"""How much context to retrieve per result. Defaults to medium (15000 chars). Only applies when using the Exa engine; ignored with native provider search."""
    user_location: NotRequired[WebSearchShorthandUserLocationTypedDict]
    r"""Approximate user location for location-biased results."""
    allowed_domains: NotRequired[List[str]]
    r"""Limit search results to these domains. Only applies when using the Exa engine; ignored with native provider search."""
    excluded_domains: NotRequired[List[str]]
    r"""Exclude search results from these domains. Only applies when using the Exa engine; ignored with native provider search."""
    parameters: NotRequired[WebSearchShorthandParametersTypedDict]


class WebSearchShorthand(BaseModel):
    r"""Web search tool using OpenAI Responses API syntax. Automatically converted to openrouter:web_search."""

    type: Annotated[WebSearchShorthandType, PlainValidator(validate_open_enum(False))]

    engine: Annotated[
        Optional[WebSearchShorthandEngine], PlainValidator(validate_open_enum(False))
    ] = None
    r"""Which search engine to use. \"auto\" (default) uses native if the provider supports it, otherwise Exa. \"native\" forces the provider's built-in search (parameters like max_results, search_context_size, and domain filters are not forwarded to the provider). \"exa\" forces the Exa search API."""

    max_results: Optional[float] = None
    r"""Maximum number of search results to return per search call. Defaults to 5. Only applies when using the Exa engine; ignored with native provider search."""

    max_total_results: Optional[float] = None
    r"""Maximum total number of search results across all search calls in a single request. Once this limit is reached, the tool will stop returning new results. Useful for controlling cost and context size in agentic loops."""

    search_context_size: Annotated[
        Optional[WebSearchShorthandSearchContextSize],
        PlainValidator(validate_open_enum(False)),
    ] = None
    r"""How much context to retrieve per result. Defaults to medium (15000 chars). Only applies when using the Exa engine; ignored with native provider search."""

    user_location: Optional[WebSearchShorthandUserLocation] = None
    r"""Approximate user location for location-biased results."""

    allowed_domains: Optional[List[str]] = None
    r"""Limit search results to these domains. Only applies when using the Exa engine; ignored with native provider search."""

    excluded_domains: Optional[List[str]] = None
    r"""Exclude search results from these domains. Only applies when using the Exa engine; ignored with native provider search."""

    parameters: Optional[WebSearchShorthandParameters] = None
