"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import date
from openrouter.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class XSearchOptionsTypedDict(TypedDict):
    r"""Enable SpaceXAI X (Twitter) search alongside native web search, with optional filters. Only applies to SpaceXAI endpoints with native search; omit to search the web only. X search is billed separately by SpaceXAI, per post and per user profile fetched."""

    allowed_x_handles: NotRequired[List[str]]
    r"""Only include posts from these X handles (max 20). Cannot be used with excluded_x_handles."""
    enable_image_understanding: NotRequired[bool]
    r"""Analyze images attached to matching posts."""
    enable_video_understanding: NotRequired[bool]
    r"""Analyze videos attached to matching posts."""
    excluded_x_handles: NotRequired[List[str]]
    r"""Exclude posts from these X handles (max 20). Cannot be used with allowed_x_handles."""
    from_date: NotRequired[date]
    r"""Start of the post date range (ISO 8601 date, e.g. \"2025-01-01\")."""
    to_date: NotRequired[date]
    r"""End of the post date range (ISO 8601 date, e.g. \"2025-12-31\")."""


class XSearchOptions(BaseModel):
    r"""Enable SpaceXAI X (Twitter) search alongside native web search, with optional filters. Only applies to SpaceXAI endpoints with native search; omit to search the web only. X search is billed separately by SpaceXAI, per post and per user profile fetched."""

    allowed_x_handles: Optional[List[str]] = None
    r"""Only include posts from these X handles (max 20). Cannot be used with excluded_x_handles."""

    enable_image_understanding: Optional[bool] = None
    r"""Analyze images attached to matching posts."""

    enable_video_understanding: Optional[bool] = None
    r"""Analyze videos attached to matching posts."""

    excluded_x_handles: Optional[List[str]] = None
    r"""Exclude posts from these X handles (max 20). Cannot be used with allowed_x_handles."""

    from_date: Optional[date] = None
    r"""Start of the post date range (ISO 8601 date, e.g. \"2025-01-01\")."""

    to_date: Optional[date] = None
    r"""End of the post date range (ISO 8601 date, e.g. \"2025-12-31\")."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "allowed_x_handles",
                "enable_image_understanding",
                "enable_video_understanding",
                "excluded_x_handles",
                "from_date",
                "to_date",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
